"""Generates src/NDSharp.Wavelets/WaveletFilters.g.cs from PyWavelets: dec/rec filter banks of every
discrete wavelet (haar, dbN, symN, coifN, biorX.Y, rbioX.Y, dmey)."""
import pywt, os
names = pywt.wavelist(kind="discrete")
lines = ["// <auto-generated> by tools/oracle/gen_wavelets.py from PyWavelets " + pywt.__version__ + " — do not edit. </auto-generated>",
         "namespace NDSharp.Wavelets;", "", "internal static class WaveletFilters", "{",
         "    public static readonly (string Name, double[] DecLo, double[] DecHi, double[] RecLo, double[] RecHi, bool Orthogonal)[] All =", "    {"]
def arr(v): return "new double[] { " + ", ".join(repr(float(x)) for x in v) + " }"
for n in names:
    w = pywt.Wavelet(n)
    lines.append(f'        ("{n}", {arr(w.dec_lo)}, {arr(w.dec_hi)}, {arr(w.rec_lo)}, {arr(w.rec_hi)}, {"true" if w.orthogonal else "false"}),')
lines += ["    };", "}"]
out = os.path.join(os.path.dirname(__file__), "..", "..", "src", "NDSharp.Wavelets", "WaveletFilters.g.cs")
open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(len(names), "wavelets")
