"""Generates src/PySharpLib.Cv2/Cv2Constants.g.cs from the real cv2 module: every integer/float module
constant (COLOR_*, THRESH_*, MORPH_*, ...) with its exact value."""
import cv2, os
items = []
for name in sorted(dir(cv2)):
    if name.startswith("_") or not (name.isupper() or name[0].isupper() and "_" in name):
        continue
    v = getattr(cv2, name)
    if isinstance(v, bool): continue
    if isinstance(v, int): items.append((name, f"{v}L"))
    elif isinstance(v, float): items.append((name, repr(v)))
out = os.path.join(os.path.dirname(__file__), "..", "..", "src", "PySharpLib.Cv2", "Cv2Constants.g.cs")
lines = ["// <auto-generated> by tools/oracle/gen_cv2_constants.py from cv2 " + cv2.__version__ + " — do not edit. </auto-generated>",
         "namespace PySharpLib.Cv2;", "", "internal static class Cv2Constants", "{",
         "    public static readonly (string Name, object Value)[] All =", "    {"]
for n, v in items:
    lines.append(f'        ("{n}", {v}),')
lines += ["    };", "}"]
open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(len(items), "constants")
