"""Generates src/NDSharp.Plot/Colormaps.g.cs (256-entry LUTs / listed colors) from the real matplotlib, and copies
the DejaVu fonts matplotlib ships (Bitstream Vera license) next to it for the renderer."""
import matplotlib, matplotlib.pyplot as plt, numpy as np, os, shutil
from matplotlib import colormaps
names = ["gray", "viridis", "plasma", "magma", "inferno", "cividis", "jet", "hot", "hsv", "rainbow", "coolwarm", "bwr", "seismic",
         "RdBu", "RdYlBu", "RdYlGn", "Spectral", "PiYG", "PRGn", "BrBG", "Blues", "Reds", "Greens", "Oranges", "Purples", "Greys", "YlOrRd", "YlGnBu",
         "bone", "copper", "cool", "spring", "summer", "autumn", "winter", "binary", "turbo", "twilight", "nipy_spectral", "afmhot", "gist_gray", "Wistia",
         "tab10", "tab20", "Set1", "Set2", "Set3", "Paired", "Pastel1", "Dark2", "Accent", "terrain", "ocean", "gnuplot", "flag", "prism"]
here = os.path.dirname(__file__)
out = os.path.join(here, "..", "..", "src", "NDSharp.Plot", "Colormaps.g.cs")
lines = ["// <auto-generated> by tools/oracle/gen_colormaps.py from matplotlib " + matplotlib.__version__ + " — do not edit. </auto-generated>",
         "namespace NDSharp.Plot;", "", "internal static class ColormapData", "{",
         "    /// <summary>name → (listed, RGB floats r0 g0 b0 r1 g1 b1 ...). Listed maps pick colors by index, others interpolate.</summary>",
         "    public static readonly (string Name, bool Listed, float[] Rgb)[] All =", "    {"]
for n in names:
    cm = colormaps[n]
    listed = type(cm).__name__ == "ListedColormap" and cm.N <= 20 and n not in ("viridis", "plasma", "magma", "inferno", "cividis", "twilight", "turbo")
    N = cm.N if listed else 256
    arr = cm(np.linspace(0, 1, N) if not listed else np.arange(N) / (N - 1 if N > 1 else 1))[:, :3] if not listed else np.array(cm.colors)[:, :3]
    if not listed:
        arr = cm(np.arange(256))[:, :3]   # the exact 256-entry LUT matplotlib uses
    flat = ", ".join(f"{v:.6f}f" for v in np.asarray(arr).ravel())
    lines.append(f'        ("{n}", {"true" if listed else "false"}, new float[] {{ {flat} }}),')
lines += ["    };", "}"]
open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
fonts = os.path.join(matplotlib.get_data_path(), "fonts", "ttf")
for f in ("DejaVuSans.ttf", "DejaVuSans-Bold.ttf", "DejaVuSans-Oblique.ttf"):
    shutil.copy(os.path.join(fonts, f), os.path.join(here, "..", "..", "src", "NDSharp.Plot", "Fonts", f))
print(len(names), "colormaps; fonts copied from", fonts)
