"""Copies the pure-Python parts of torchvision (BSD-3-Clause, https://github.com/pytorch/vision) that PySharp.Torch needs from the oracle
venv into src/PySharpLib.Torch/py/, rewriting relative imports to absolute ones. Files that depend on compiled extensions or on PIL are
hand-written instead (see the *.py files in that folder without the "GENERATED" header).

    tools/oracle/.venv/Scripts/python.exe tools/oracle/gen_torchvision.py
"""
import os
import re
import sys

root = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
src = os.path.join(os.path.dirname(sys.executable), "..", "Lib", "site-packages", "torchvision")
src = os.path.normpath(src)
out = os.path.join(root, "src", "PySharpLib.Torch", "py")

# real path (relative to torchvision/) -> module name
FILES = {
    "models/_api.py": "torchvision.models._api",
    "models/_meta.py": "torchvision.models._meta",
    "models/_utils.py": "torchvision.models._utils",
    "models/resnet.py": "torchvision.models.resnet",
    "models/mobilenet.py": "torchvision.models.mobilenet",
    "models/mobilenetv2.py": "torchvision.models.mobilenetv2",
    "models/mobilenetv3.py": "torchvision.models.mobilenetv3",
    "transforms/_presets.py": "torchvision.transforms._presets",
    "models/segmentation/_utils.py": "torchvision.models.segmentation._utils",
    "models/segmentation/fcn.py": "torchvision.models.segmentation.fcn",
    "ops/misc.py": "torchvision.ops.misc",
    "ops/_box_convert.py": "torchvision.ops._box_convert",
    "ops/_utils.py": "torchvision.ops._utils",
    "ops/giou_loss.py": "torchvision.ops.giou_loss",
    "ops/diou_loss.py": "torchvision.ops.diou_loss",
    "ops/ciou_loss.py": "torchvision.ops.ciou_loss",
    "ops/feature_pyramid_network.py": "torchvision.ops.feature_pyramid_network",
    "ops/poolers.py": "torchvision.ops.poolers",
    "models/detection/_utils.py": "torchvision.models.detection._utils",
    "models/detection/anchor_utils.py": "torchvision.models.detection.anchor_utils",
    "models/detection/backbone_utils.py": "torchvision.models.detection.backbone_utils",
    "models/detection/faster_rcnn.py": "torchvision.models.detection.faster_rcnn",
    "models/detection/generalized_rcnn.py": "torchvision.models.detection.generalized_rcnn",
    "models/detection/image_list.py": "torchvision.models.detection.image_list",
    "models/detection/mask_rcnn.py": "torchvision.models.detection.mask_rcnn",
    "models/detection/roi_heads.py": "torchvision.models.detection.roi_heads",
    "models/detection/rpn.py": "torchvision.models.detection.rpn",
    "models/detection/transform.py": "torchvision.models.detection.transform",
}

HEADER = ("# GENERATED by tools/oracle/gen_torchvision.py from torchvision {ver} ({rel}); BSD-3-Clause, Copyright (c) Soumith Chintala 2016.\n"
          "# Do not edit by hand: change the generator or add a hand-written override instead.\n")


def absolutize(text, module):
    pkg = module.rsplit(".", 1)[0]  # the file is a plain module: its package is the parent

    def fix(m):
        dots, rest = m.group(1), m.group(2)
        parts = pkg.split(".")
        base = parts[: len(parts) - (len(dots) - 1)]
        return "from " + ".".join(base + ([rest] if rest else [])) + " import "

    return re.sub(r"^from (\.+)([\w.]*) import ", fix, text, flags=re.M)


def main():
    import torchvision
    only = sys.argv[1:]
    for rel, module in FILES.items():
        if only and not any(o in module for o in only):
            continue
        path = os.path.join(src, *rel.split("/"))
        if not os.path.exists(path):
            print("missing", rel)
            continue
        text = open(path, encoding="utf-8").read()
        text = absolutize(text, module)
        with open(os.path.join(out, module + ".py"), "w", encoding="utf-8", newline="\n") as f:
            f.write(HEADER.format(ver=torchvision.__version__, rel=rel) + text)
        print("wrote", module)


if __name__ == "__main__":
    main()
