<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PySharpLib\PySharpLib.csproj" />
    <ProjectReference Include="..\..\src\PySharpLib.Numpy\PySharpLib.Numpy.csproj" />
    <ProjectReference Include="..\..\src\PySharpLib.Cv2\PySharpLib.Cv2.csproj" />
    <ProjectReference Include="..\..\src\PySharpLib.Pywt\PySharpLib.Pywt.csproj" />
    <ProjectReference Include="..\..\src\PySharpLib.Matplotlib\PySharpLib.Matplotlib.csproj" />
    <ProjectReference Include="..\..\src\PySharpLib.Torch\PySharpLib.Torch.csproj" />
  </ItemGroup>

</Project>
