import pandas as pd

df = pd.DataFrame({'a': [1, 2], 'b': [[1, 2], {'k': 1}], 'c': [None, 'x'], 'd': [1.5, None]})
print(df)
print(df.dtypes)
long = pd.DataFrame({'t': ['x' * 60, 'short'], 'n': [1, 2]})
print(long)
print(pd.Series([], name='nm', dtype='int64'))
print(pd.Series([1.5, 2.5], index=[0.5, 1.5]))
print(pd.Series([1, 2, 3], index=[-1, 0, 1]))
print(pd.Series([-1, -22, 333]))
print(pd.Series(['é', 'ü', 'ñ']))
print(pd.Series([True, None, False]))
print(pd.Series([1.0, None, 3.0]).tolist())
print(pd.Series(['a', None]).tolist())
print(pd.DataFrame({'a': [1, 2]}, index=pd.Index([1, 2], name='i')))
df2 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
df2.columns = ['x', 'y']
df2.index = ['p', 'q']
print(df2)
df2.columns.name = 'letters'
print(df2)
print(pd.DataFrame({'a': [1, 2], 'b': [3, 4]}, columns=['b', 'a']))
print(pd.DataFrame({'a': [1, 2]}, columns=['a', 'z']))
print(df2.iloc[:0])
print(df2[df2['x'] > 5] if False else df2.iloc[[]])
print(pd.DataFrame({'a': [1, 2], 'b': [3, 4]}).values)
print(pd.DataFrame({'a': [1, 2], 'b': [3.5, 4]}).values)
print(pd.Series([1, 2, 3]).values)
pd.set_option('display.max_columns', 5)
print(pd.DataFrame({'c%d' % j: [j, j * 2] for j in range(12)}))
pd.set_option('display.max_columns', 0)
pd.set_option('display.width', 40)
print(pd.DataFrame({'col%d' % j: [j * 1.5, j * 2.5] for j in range(8)}))
