import pandas as pd

df = pd.DataFrame({'a': [1, 2, 3], 'b': [1.5, 2.5, None], 'c': ['x', None, 'zz'], 'd': [True, False, True]})
print(df)
print(df.dtypes)
print(df.shape, df.size, len(df), df.ndim)
print(df.columns)
print(df.index)
print(list(df.columns))
print(pd.DataFrame([[1, 2], [3, 4]]))
print(pd.DataFrame([[1, 2], [3, 4]], columns=['p', 'q'], index=['r1', 'r2']))
print(pd.DataFrame([{'a': 1, 'b': 2}, {'a': 3, 'c': 4}]))
print(pd.DataFrame({'a': [1, 2]}, index=['u', 'v']))
print(pd.DataFrame())
print(pd.DataFrame({'a': [], 'b': []}))
print(pd.DataFrame({'x': 1.0, 'y': 'k'}, index=[0, 1]))
print(df.head(2))
print(df.tail(1))
print(df.empty)
