import pandas as pd

s = pd.Series([1, 2, 3])
print(s)
print(s.dtype, s.shape, s.size, len(s), s.name)
print(pd.Series([1.5, 2.0, None]))
print(pd.Series([1, 2, None]))
print(pd.Series(['a', 'bb', None, 'dddd']))
print(pd.Series([True, False, True]))
print(pd.Series([1, 'a', 2.5]))
print(pd.Series([1, 2, 3], index=['x', 'y', 'z'], name='vals'))
print(pd.Series({'b': 1, 'a': 2}))
print(pd.Series(5, index=[10, 20, 30]))
print(pd.Series([], dtype='float64'))
print(pd.Series([1, 2, 3], dtype='float64'))
print(pd.Series([0.1, 0.25, 100.0]))
print(pd.Series([1e-10, 1.0]))
print(pd.Series([1e10, 1.0]))
print(pd.Series([-1.5, 2.25, -3.0]))
print(repr(s))
print(s.index)
print(s.tolist())
print(s.head(2))
print(s.tail(2))
