import pandas as pd

a = pd.Series([1, 2, 3], index=['x', 'y', 'z'])
b = pd.Series([10, 20, 30], index=['y', 'z', 'w'])
print(a + b)
print(a * b)
print(a - b)
print(a / b)
c = pd.Series([1.5, 2.5], index=[2, 1])
d = pd.Series([1, 2, 3], index=[1, 2, 3])
print(c + d)
print(pd.Series([1, 2], index=['a', 'b'], name='n') + pd.Series([3, 4], index=['a', 'b'], name='n'))
print(pd.Series([1, 2], index=['a', 'b'], name='n') + pd.Series([3, 4], index=['a', 'b'], name='m'))
f1 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]}, index=['r1', 'r2'])
f2 = pd.DataFrame({'b': [10, 20], 'c': [30, 40]}, index=['r2', 'r3'])
print(f1 + f2)
print(f1 * 2)
print(f1 + pd.Series([100, 200], index=['a', 'b']))
print(f1.add(pd.Series([100, 200], index=['r1', 'r2']), axis=0))
print(f1 - f1)
print(f1 / 2)
print(1 + f1)
print(f1 + [1, 2])
print(f1.pow(2))
print(f1 // 2, f1 % 2)
print(-f1)
print(f1 + f1.T.T)
dup = pd.Series([1, 2], index=['a', 'a'])
print(dup + dup)
