import pandas as pd
import math

s = pd.Series([1.0, None, 3.0, None])
print(s.isna(), s.notna(), s.isnull())
print(s.fillna(0))
print(s.fillna(-1.5))
print(s.ffill(), s.bfill())
print(s.dropna())
print(pd.Series(['a', None, 'c']).fillna('?'))
print(pd.Series(['a', None, 'c']).isna())
df = pd.DataFrame({'a': [1, None, 3, None], 'b': [None, 'x', 'y', None], 'c': [1.5, 2.5, None, None]})
print(df.isna())
print(df.isna().sum())
print(df.fillna(0))
print(df.fillna({'a': -1, 'b': 'none'}))
print(df.dropna())
print(df.dropna(how='all'))
print(df.dropna(subset=['a']))
print(df.dropna(axis=1))
print(df.dropna(axis=1, how='all'))
print(df.dropna(thresh=2))
print(df.ffill())
print(df.bfill())
print(pd.isna(math.nan), pd.isna(None), pd.isna(1), pd.notna(2.5))
print(pd.isna([1, None, math.nan]))
x = pd.Series([1, 2, 3, 4])
print(x.where(x > 2))
print(x.where(x > 2, 0))
print(x.mask(x > 2))
print(x.mask(x > 2, -1))
print(x.replace(2, 20), x.replace([1, 2], 0), x.replace({3: 30, 4: 40}), x.replace([1, 2], [10, 20]))
print(pd.Series(['a', 'b', 'a']).replace('a', 'z'))
print(x.clip(2, 3), x.clip(lower=3), x.clip(upper=2))
print(pd.Series([1.234, 5.678, 2.5, 3.5]).round(1), pd.Series([1.234, 5.678, 2.5, 3.5]).round(), pd.Series([1234, 5678]).round(-2))
print(df['a'].fillna(df['a'].mean()))
d2 = pd.DataFrame({'p': [1, 2, 3], 'q': [4, 5, 6]})
print(d2.where(d2 > 2), d2.mask(d2 > 2, 0), d2.clip(2, 5), d2.replace(2, 99), d2.round(1))
s2 = pd.Series([1, None, 3.0])
s2.fillna(0, inplace=True)
print(s2)
d3 = pd.DataFrame({'a': [1, None]})
d3.dropna(inplace=True)
print(d3)
