import numpy as np
import pandas as pd

s = pd.Series([1.0, 4.0, 9.0], index=['a', 'b', 'c'], name='v')
print(np.sqrt(s))
print(np.log(s))
print(np.mean(s), np.sum(s), np.max(s))
print(s.values * 2)
print(np.asarray(s))
print(pd.Series(np.arange(5)))
print(pd.Series(np.array([0.5, 1.5])))
df = pd.DataFrame(np.arange(6).reshape(3, 2), columns=['x', 'y'])
print(df)
print(df.values)
print(np.asarray(df))
print(np.sqrt(df))
print(df.to_numpy().sum())
rng = np.random.default_rng(0)
d = pd.DataFrame(rng.normal(size=(5, 3)), columns=list('abc'))
print(d)
print(d.describe())
print(d.mean())
print(d.corr())
print(round(d['a'].corr(d['b']), 10))
print(d.cov())
print(np.add(s, 1))
print(s + np.array([1, 2, 3]))
print(np.array([1, 2, 3]) + s)
print(pd.DataFrame({'a': [1, 2, 3], 'b': [0.5, 1.5, 2.5]}).info())
print(pd.Series([1, 2, 3]).info())
x = pd.DataFrame({'a': [1, None], 's': ['x', 'y']})
x.info()
