import pandas as pd

s = pd.Series([3, 1, 4, 1, 5, 9, 2, 6])
print(s.sum(), s.mean(), s.median(), s.min(), s.max(), s.count(), s.prod())
print(s.std(), s.var(), s.std(ddof=0), s.var(ddof=0))
print(s.nunique(), s.idxmax(), s.idxmin())
print(s.quantile(0.25), s.quantile([0.1, 0.5, 0.9]))
f = pd.Series([1.5, None, 2.5, 4.0])
print(f.sum(), f.mean(), f.min(), f.max(), f.count(), f.std(), f.median())
print(f.sum(skipna=False), f.mean(skipna=False), f.max(skipna=False))
print(pd.Series([], dtype='float64').sum(), pd.Series([], dtype='float64').mean(), pd.Series([], dtype='int64').sum())
print(pd.Series([True, False, True]).sum(), pd.Series([True, False, True]).mean(), pd.Series([True, False]).any(), pd.Series([True, False]).all())
print(pd.Series(['b', 'a', 'c']).min(), pd.Series(['b', 'a', 'c']).max(), pd.Series(['x', 'y']).sum(), pd.Series(['a', None, 'a']).nunique(), pd.Series(['a', None, 'a']).count())
print(pd.Series([0.1] * 10).sum(), pd.Series([0.1 * i for i in range(1, 101)]).sum(), pd.Series([0.1 * i for i in range(1, 101)]).mean(), pd.Series([0.1 * i for i in range(1, 101)]).std())
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4.5, None, 6.0], 'c': [True, False, True]})
print(df.sum())
print(df.mean())
print(df.min(), df.max(), df.count())
print(df[['a', 'b']].std())
print(df.sum(axis=1))
print(df.mean(axis=1))
print(df.median())
print(df.idxmax(), df.nunique())
print(df[['a', 'b']].quantile(0.5))
print(df[['a', 'b']].quantile([0.25, 0.75]))
print(df[['a', 'b']].prod())
print(df.sum(numeric_only=True))
print(pd.DataFrame({'a': [1, 2], 's': ['x', 'y']}).sum())
print(pd.DataFrame({'a': [1, 2], 's': ['x', 'y']}).count())
print(df.any(), df.all())
try:
    pd.Series(['a', 'b']).mean()
except TypeError as e:
    print('TypeError')
