import pandas as pd

s = pd.Series(['Apple', 'banana', None, '  Cherry pie  ', 'date'])
print(s.str.lower())
print(s.str.upper())
print(s.str.title())
print(s.str.capitalize())
print(s.str.strip())
print(s.str.lstrip(), s.str.rstrip())
print(s.str.len())
print(s.str.contains('an'))
print(s.str.contains('^a', case=False))
print(s.str.contains('a.a', regex=False))
print(s.str.startswith('b'), s.str.endswith('e'))
print(s.str.replace('a', 'A'))
print(s.str.replace('[aeiou]', '#', regex=True))
print(s.str.count('a'))
print(s.str.find('a'))
print(s.str.slice(0, 3), s.str.slice(1), s.str.slice(None, None, 2))
print(s.str.get(0), s.str.get(-1))
print(s.str.split('a'))
print(s.str.split(' '))
print(s.str.split('a', expand=True))
print(pd.Series(['a b c', 'd e']).str.split())
print(pd.Series(['a-b-c']).str.split('-', n=1))
print(pd.Series(['1', '22', 'x3']).str.isdigit(), pd.Series(['ab', 'a1']).str.isalpha(), pd.Series(['AB', 'Ab']).str.isupper(), pd.Series(['ab', 'Ab']).str.islower())
print(pd.Series(['7', '42']).str.zfill(4), pd.Series(['a', 'bb']).str.pad(4), pd.Series(['a', 'bb']).str.pad(4, side='right', fillchar='*'), pd.Series(['a']).str.center(5, '-'))
print(pd.Series(['ab', 'c']).str.repeat(2))
print(pd.Series(['foo.py', 'bar.txt']).str.removesuffix('.py'), pd.Series(['xfoo', 'bar']).str.removeprefix('x'))
print(pd.Series(['a', 'b', 'c']).str.cat(sep=','))
print(pd.Series(['a', 'b']).str.cat(pd.Series(['1', '2']), sep='-'))
print(pd.Series(['a1', 'b2']).str.replace(r'(\w)(\d)', r'\2\1', regex=True))
print(pd.Series(['abc', 'abd']).str.match('ab'), pd.Series(['abc', 'xab']).str.match('ab'))
print(s.str.len().sum(), s.str.lower().tolist())
print(pd.DataFrame({'n': ['Ann Lee', 'Bob Ray']})['n'].str.split(' ', expand=True))
df = pd.DataFrame({'name': ['ann', 'bob'], 'age': [30, 25]})
df['name'] = df['name'].str.title()
print(df)
print(df[df['name'].str.startswith('B')])
try:
    pd.Series([1, 2]).str.lower()
except AttributeError as e:
    print('AttributeError')
