import pandas as pd

s = pd.Series([3, 1, 2, 1], index=['a', 'b', 'c', 'd'])
print(s.sort_values())
print(s.sort_values(ascending=False))
print(s.sort_index())
print(s.sort_index(ascending=False))
print(pd.Series([2.0, None, 1.0]).sort_values())
print(pd.Series([2.0, None, 1.0]).sort_values(na_position='first'))
print(pd.Series(['b', 'a', 'C']).sort_values())
print(s.nlargest(2), s.nsmallest(2))
print(s.unique(), s.nunique())
print(pd.Series([1, 1, 2, 3, 3]).unique())
print(s.value_counts())
print(pd.Series(['x', 'y', 'x', 'z', 'x', 'y']).value_counts())
print(pd.Series(['x', 'y', 'x']).value_counts(normalize=True))
print(pd.Series(['x', 'y', 'x', 'y']).value_counts(ascending=True))
print(pd.Series([1.5, None, 1.5]).value_counts(), pd.Series([1.5, None, 1.5]).value_counts(dropna=False))
print(pd.Series([1, 2, 1, 3, 2]).duplicated(), pd.Series([1, 2, 1, 3, 2]).duplicated(keep='last'), pd.Series([1, 2, 1]).duplicated(keep=False))
print(pd.Series([1, 2, 1, 3, 2]).drop_duplicates())
df = pd.DataFrame({'k': ['b', 'a', 'b', 'a'], 'v': [4, 3, 2, 1], 'w': [1.0, 2.0, 3.0, 4.0]})
print(df.sort_values('v'))
print(df.sort_values(['k', 'v']))
print(df.sort_values(['k', 'v'], ascending=[True, False]))
print(df.sort_values('k', ascending=False))
print(df.sort_values('v', ignore_index=True))
print(df.sort_index(ascending=False))
print(df.sort_index(axis=1, ascending=False))
print(df.nlargest(2, 'v'), df.nsmallest(2, 'w'))
print(df.duplicated(), df.duplicated(subset=['k']), df.drop_duplicates(subset=['k']), df.drop_duplicates(subset=['k'], keep='last'))
print(df.reset_index(), df.reset_index(drop=True))
print(df.set_index('k'))
print(df.set_index('k', drop=False))
print(df.set_index('k').reset_index())
print(df.set_index('k').sort_index())
print(s.reset_index(), s.reset_index(drop=True))
print(pd.Series([5, 6], name='n').reset_index())
print(df.rename(columns={'k': 'key', 'v': 'val'}))
print(df.rename(index={0: 'zero', 3: 'three'}))
print(df.rename(columns=str.upper))
print(s.rename('new'), s.rename({'a': 'A'}))
print(df.T)
print(df[['v', 'w']].T)
