import pandas as pd

df = pd.DataFrame({
    'team': ['red', 'blue', 'red', 'blue', 'red', 'green'],
    'kind': ['a', 'a', 'b', 'b', 'a', 'a'],
    'pts': [10, 20, 30, 40, 50, 60],
    'avg': [1.5, 2.5, None, 4.5, 5.5, 6.5],
})
g = df.groupby('team')
print(g.sum())
print(g.mean(numeric_only=True))
print(g[['pts', 'avg']].mean())
print(g['pts'].sum())
print(g['pts'].mean(), g['avg'].count())
print(g.size())
print(g.count())
print(g['pts'].max(), g['pts'].min(), g['pts'].median(), g['pts'].std(), g['pts'].var())
print(g['pts'].first(), g['pts'].last(), g['pts'].nunique())
print(g.ngroups, len(g))
print(df.groupby(['team', 'kind']).sum())
print(df.groupby(['team', 'kind'])['pts'].sum())
print(df.groupby(['team', 'kind'])['pts'].mean().reset_index())
print(df.groupby('team', as_index=False)['pts'].sum())
print(df.groupby('team', as_index=False).agg({'pts': 'sum', 'avg': 'mean'}))
print(df.groupby('team', sort=False)['pts'].sum())
print(g.agg({'pts': 'sum', 'avg': 'mean'}))
print(g.agg({'pts': ['sum', 'max'], 'avg': 'min'}))
print(g['pts'].agg(['sum', 'mean', 'count']))
print(g.agg(total=('pts', 'sum'), best=('avg', 'max')))
print(g['pts'].agg(lambda s: s.max() - s.min()))
print(g[['pts']].agg(['min', 'max']))
for key, grp in g:
    print(key, grp.shape, grp['pts'].tolist())
for key, grp in df.groupby(['team', 'kind']):
    print(key, len(grp))
print(g.get_group('red'))
print(g.groups)
print(g['pts'].transform('sum'))
print(g['pts'].transform(lambda s: s - s.mean()))
print(g[['pts', 'avg']].transform('max'))
print(g['pts'].cumsum(), g['pts'].cumcount(), g['pts'].shift(1), g['pts'].diff())
print(g.filter(lambda x: x['pts'].sum() > 50))
print(g.apply(lambda x: x['pts'].sum()))
print(g.apply(lambda x: x[['pts']].max()))
print(g.head(1), g.tail(1))
print(df.groupby(df['team'].str.len())['pts'].sum())
print(df.groupby([df['pts'] > 25, 'team'])['pts'].count())
print(df.set_index('team').groupby(level=0)['pts'].sum())
print(df['pts'].groupby(df['team']).sum())
print(df['pts'].groupby(df['team']).agg(['min', 'max']))
nan = pd.DataFrame({'k': ['a', None, 'a', 'b'], 'v': [1, 2, 3, 4]})
print(nan.groupby('k')['v'].sum(), nan.groupby('k', dropna=False)['v'].sum())
print(df.groupby('team')['pts'].quantile(0.5))
print(g.any if False else g['pts'].apply(lambda s: s.tolist()))
print(df.groupby('kind').agg(n=('pts', 'size'), total=('pts', 'sum')))
