import io
import os
import tempfile
import pandas as pd

text = "id,name,score,ok\n1,Ann,3.5,True\n2,Bob,,False\n3,\"Lee, Jr\",7.25,True\n"
df = pd.read_csv(io.StringIO(text))
print(df)
print(df.dtypes)
print(pd.read_csv(io.StringIO(text), index_col='id'))
print(pd.read_csv(io.StringIO(text), index_col=0).index)
print(pd.read_csv(io.StringIO(text), usecols=['name', 'score']))
print(pd.read_csv(io.StringIO(text), usecols=[0, 2]))
print(pd.read_csv(io.StringIO(text), nrows=2))
print(pd.read_csv(io.StringIO(text), dtype={'id': str}))
print(pd.read_csv(io.StringIO(text), dtype={'id': 'float64'}).dtypes)
print(pd.read_csv(io.StringIO(text), skiprows=1, header=None))
print(pd.read_csv(io.StringIO("1,2\n3,4\n"), header=None))
print(pd.read_csv(io.StringIO("1,2\n3,4\n"), names=['p', 'q']))
print(pd.read_csv(io.StringIO("a;b\n1;2\n"), sep=';'))
print(pd.read_csv(io.StringIO("a\tb\n1\t2\n"), sep='\t'))
print(pd.read_table(io.StringIO("a\tb\n1\t2\n")))
print(pd.read_csv(io.StringIO("a,b\n1,NA\n2,x\n,y\n")))
print(pd.read_csv(io.StringIO("a,b\n1,-\n2,x\n"), na_values=['-']))
print(pd.read_csv(io.StringIO("a,b\n1,-\n2,x\n"), na_values={'b': ['x']}))
print(pd.read_csv(io.StringIO("a,b\nNA,NULL\n"), keep_default_na=False))
print(pd.read_csv(io.StringIO("# note\na,b\n1,2 # tail\n"), comment='#'))
print(pd.read_csv(io.StringIO("a,a,b\n1,2,3\n")).columns.tolist())
print(pd.read_csv(io.StringIO(",x\n0,1\n1,2\n")).columns.tolist())
print(pd.read_csv(io.StringIO("a,b\n1.5,2\n3,4\n")).dtypes)
print(pd.read_csv(io.StringIO("a,b\n1,2\n3\n")))
print(pd.read_csv(io.StringIO("x\n1,000\n2,500\n"), thousands=',') if False else 'skip')
print(pd.read_csv(io.StringIO("x\n1,5\n"), decimal=',', sep=';') if False else 'skip')
print(pd.read_csv(io.StringIO("a,b\n")).shape, pd.read_csv(io.StringIO("a,b\n")).columns.tolist())
# to_csv
print(df.to_csv(lineterminator='\n'), end='')
print(df.to_csv(lineterminator='\n', index=False), end='')
print(df.to_csv(lineterminator='\n', sep=';', na_rep='NA', index=False), end='')
print(df.to_csv(lineterminator='\n', columns=['name', 'score'], index=False), end='')
print(df.to_csv(lineterminator='\n', header=False), end='')
print(df.to_csv(lineterminator='\n', index_label='row'), end='')
print(df.to_csv(lineterminator='\n', float_format='%.1f', index=False), end='')
print(pd.DataFrame({'a': [1.0, 2.5, 1e-7, 1e20], 'b': ['x,y', 'q"r', 'line\nbreak', None]}).to_csv(lineterminator='\n', index=False), end='')
print(pd.Series([1, 2], name='n').to_csv(lineterminator='\n'), end='')
print(pd.Series([1.5, None], index=['a', 'b']).to_csv(lineterminator='\n'), end='')
mi = pd.DataFrame({'v': [1, 2]}, index=pd.MultiIndex.from_tuples([('a', 1), ('b', 2)], names=['k1', 'k2']))
print(mi.to_csv(lineterminator='\n'), end='')
d = os.path.join(tempfile.gettempdir(), 'pysharp_pandas_io_test.csv')
df.to_csv(d, index=False, lineterminator='\n')
back = pd.read_csv(d)
print(back.equals(df), back.shape)
os.remove(d)
rt = pd.read_csv(io.StringIO(df.to_csv(lineterminator='\n')), index_col=0)
print(rt)
# dicts
print(df.to_dict())
print(df.to_dict('list'))
print(df.to_dict('records'))
print(df.to_dict('index'))
print(df.to_dict('split'))
print(df.to_dict('tight'))
print(df['name'].to_dict())
print(pd.DataFrame.from_dict({'a': [1, 2], 'b': [3, 4]}))
print(pd.DataFrame.from_dict({'r1': {'x': 1, 'y': 2}, 'r2': {'x': 3, 'y': 4}}, orient='index'))
print(pd.DataFrame.from_dict({'r1': [1, 2], 'r2': [3, 4]}, orient='index', columns=['x', 'y']))
print(pd.DataFrame.from_records([(1, 'a'), (2, 'b')], columns=['n', 's']))
print(pd.DataFrame.from_records([{'n': 1}, {'n': 2}]))
print(pd.DataFrame(df.to_dict('records')).equals(df))
