import pandas as pd

a = pd.DataFrame({'k': ['x', 'y', 'z', 'x'], 'va': [1, 2, 3, 4]})
b = pd.DataFrame({'k': ['x', 'z', 'w'], 'vb': [10.0, 30.0, 40.0]})
print(pd.merge(a, b, on='k'))
print(pd.merge(a, b, on='k', how='left'))
print(pd.merge(a, b, on='k', how='right'))
print(pd.merge(a, b, on='k', how='outer'))
print(a.merge(b, on='k', how='inner'))
print(a.merge(b))
print(pd.merge(a, b, on='k', how='outer', indicator=True))
c = pd.DataFrame({'key': ['x', 'y'], 'val': [1, 2]})
d = pd.DataFrame({'id': ['x', 'x', 'q'], 'val': [5, 6, 7]})
print(pd.merge(c, d, left_on='key', right_on='id'))
print(pd.merge(c, d, left_on='key', right_on='id', suffixes=('_l', '_r')))
print(pd.merge(c, d, left_on='key', right_on='id', how='left'))
two = pd.DataFrame({'a': [1, 1, 2], 'b': ['p', 'q', 'p'], 'v': [1, 2, 3]})
two2 = pd.DataFrame({'a': [1, 2, 2], 'b': ['p', 'p', 'q'], 'w': [10, 20, 30]})
print(pd.merge(two, two2, on=['a', 'b']))
print(pd.merge(two, two2, on=['a', 'b'], how='outer'))
print(pd.merge(a, b, how='cross').shape)
li = pd.DataFrame({'v1': [1, 2, 3]}, index=['a', 'b', 'c'])
ri = pd.DataFrame({'v2': [10, 20, 30]}, index=['b', 'c', 'd'])
print(li.join(ri))
print(li.join(ri, how='outer'))
print(li.join(ri, how='inner'))
print(pd.merge(li, ri, left_index=True, right_index=True, how='outer'))
print(pd.merge(a, ri, left_on='k', right_index=True, how='left') if False else 'skip')
print(li.join(pd.DataFrame({'v1': [9, 8, 7]}, index=['a', 'b', 'c']), lsuffix='_l', rsuffix='_r'))
print(a.join(b.set_index('k'), on='k'))
n1 = pd.DataFrame({'k': [1, None, 3], 'a': [1, 2, 3]})
n2 = pd.DataFrame({'k': [None, 3, 4], 'b': [4, 5, 6]})
print(pd.merge(n1, n2, on='k', how='outer'))
print(pd.merge(n1, n2, on='k'))
# concat
s1 = pd.Series([1, 2], index=['a', 'b'], name='s')
s2 = pd.Series([3, 4], index=['c', 'd'], name='s')
print(pd.concat([s1, s2]))
print(pd.concat([s1, s2], ignore_index=True))
print(pd.concat([s1, s2], keys=['one', 'two']))
print(pd.concat([s1, s2.rename('t')], axis=1))
print(pd.concat([pd.Series([1, 2]), pd.Series([3, 4])], axis=1))
f1 = pd.DataFrame({'x': [1, 2], 'y': [3.5, 4.5]})
f2 = pd.DataFrame({'y': [9.5], 'z': ['q']})
print(pd.concat([f1, f2]))
print(pd.concat([f1, f2], ignore_index=True))
print(pd.concat([f1, f2], join='inner'))
print(pd.concat([f1, f2], keys=['A', 'B']))
print(pd.concat([f1, f1 * 10], axis=1))
print(pd.concat([f1, pd.DataFrame({'w': [7, 8, 9]}, index=[1, 2, 3])], axis=1))
print(pd.concat([f1, pd.DataFrame({'w': [7, 8, 9]}, index=[1, 2, 3])], axis=1, join='inner'))
print(pd.concat({'a': f1, 'b': f1}))
print(pd.concat([f1.iloc[:1], f1.iloc[1:]]))
print(pd.concat([f1, f1]).reset_index(drop=True))
rows = [pd.DataFrame({'n': [i], 'sq': [i * i]}) for i in range(3)]
print(pd.concat(rows, ignore_index=True))
