import pandas as pd

df = pd.DataFrame({'v': [1, 2, 3, 4, 5], 'w': [1.5, 2.5, 3.5, 4.5, 5.5]}, index=pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('b', 3)]))
print(df)
df.index.names = ['k1', 'k2']
print(df)
print(df['v'])
print(df.index)
print(df.index.nlevels, df.index.names, df.index.tolist())
print(df.index.get_level_values(0), df.index.get_level_values('k2'))
print(df.loc['a'])
print(df.loc[('a', 2)])
print(df.loc[('b', 1), 'w'])
print(df.loc['b', 'v'])
print(df['v'].loc['b'], df['v'].loc[('b', 3)])
print(df.reset_index())
print(df.reset_index(drop=True))
print(df.sort_index(ascending=False))
print(df.droplevel(0) if hasattr(df, 'droplevel') else df.index.droplevel(0))
c = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns=pd.MultiIndex.from_tuples([('x', 'sum'), ('x', 'mean'), ('y', 'sum'), ('y', 'mean')]))
print(c)
c.columns.names = ['var', 'stat']
print(c)
c.index.name = 'idx'
print(c)
print(c.columns)
print(c['x'])
print(c[('y', 'sum')])
print(c.columns.tolist())
print(['_'.join(t) for t in c.columns])
print(pd.Series([1, 2, 3, 4], index=pd.MultiIndex.from_product([['p', 'q'], [1, 2]], names=['a', 'b'])))
print(pd.MultiIndex.from_arrays([['a', 'a', 'b'], [1, 2, 1]], names=['x', 'y']))
print(pd.MultiIndex.from_product([['a', 'b'], [1, 2]]))
print(df.set_index('v', append=False).index.name if False else 'ok')
flat = pd.DataFrame({'a': ['x', 'x', 'y'], 'b': [1, 2, 1], 'v': [10, 20, 30]})
m = flat.set_index(['a', 'b'])
print(m)
print(m.loc[('x', 2)], m.loc['y'])
print(flat.set_index(['a', 'b'], drop=False))
print(m.sort_index(ascending=False))
print(m.index.is_unique, len(m), m.shape)
print(m.sum(), m['v'] * 2)
print(isinstance(m.index, pd.MultiIndex), isinstance(flat.index, pd.MultiIndex))
