import pandas as pd

df = pd.DataFrame({'a': ['x', 'x', 'y', 'y', 'x'], 'b': ['p', 'q', 'p', 'q', 'p'], 'v': [1, 2, 3, 4, 5], 'w': [1.5, 2.5, 3.5, None, 5.5]})
print(df.pivot_table(values='v', index='a', columns='b'))
print(df.pivot_table(values='v', index='a', columns='b', aggfunc='sum'))
print(df.pivot_table(values=['v', 'w'], index='a', columns='b', aggfunc='sum'))
print(df.pivot_table(values='v', index='a', aggfunc=['sum', 'mean']))
print(df.pivot_table(index='a', columns='b', aggfunc='size'))
print(df.pivot_table(index=['a', 'b'], values='v', aggfunc='sum'))
print(df.pivot_table(values='v', index='a', columns='b', aggfunc='sum', margins=True))
print(df.pivot_table(values='v', index='a', columns='b', aggfunc='sum', fill_value=0, margins=True, margins_name='Total'))
print(df.pivot_table(index='a', values=['v', 'w']))
print(df.pivot_table(values='v', index='a', columns='b', aggfunc='max', fill_value=-1))
print(df.pivot_table(values='v', index='a', columns='b', aggfunc=lambda s: s.max() - s.min()))
print(pd.pivot_table(df, values='w', index='b', columns='a', aggfunc='mean'))
uniq = df.drop_duplicates(['a', 'b'])
print(uniq.pivot(index='a', columns='b', values='v'))
print(uniq.pivot(index='a', columns='b'))
print(uniq.pivot(columns='b', values='v', index='a').columns.tolist())
try:
    df.pivot(index='a', columns='b', values='v')
except ValueError as e:
    print('ValueError', e)
print(df.melt(id_vars=['a'], value_vars=['v', 'w']))
print(df.melt(id_vars=['a', 'b']))
print(df.melt(id_vars='a', value_vars='v', var_name='k', value_name='val'))
print(pd.melt(df, id_vars=['a'], value_vars=['v']))
print(pd.crosstab(df['a'], df['b']))
print(pd.crosstab(df['a'], df['b'], margins=True))
print(pd.crosstab(df['a'], df['b'], values=df['v'], aggfunc='sum'))
print(pd.crosstab(df['a'], df['b'], normalize='index'))
print(pd.crosstab(df['a'], df['b'], normalize='columns'))
print(pd.crosstab(df['a'], df['b'], normalize=True))
print(pd.crosstab(df['a'], df['b'], rownames=['A'], colnames=['B']))
s = df.groupby(['a', 'b'])['v'].sum()
print(s.unstack())
print(s.unstack(0))
print(s.unstack('a'))
print(s.unstack().stack())
print(s.unstack(fill_value=0))
print(df.groupby(['a', 'b'])[['v', 'w']].sum().unstack())
print(df.groupby(['a', 'b']).size().unstack(fill_value=0))
t = pd.DataFrame({'p': [1, 2], 'q': [3, 4]}, index=['r1', 'r2'])
print(t.stack())
print(pd.get_dummies(df['a']))
print(pd.get_dummies(df[['a', 'v']]))
print(pd.get_dummies(df['a'], drop_first=True, dtype=int))
print(pd.get_dummies(df, columns=['b']).columns.tolist())
print(pd.get_dummies(df['a'], prefix='is'))
print(pd.get_dummies(pd.Series(['u', None, 'u']), dummy_na=True))
