import numpy as np
import pandas as pd

s = pd.Series([1.0, 2.0, 4.0, 7.0, 11.0, 16.0, 22.0])
print(s.rolling(3).sum())
print(s.rolling(3).mean())
print(s.rolling(3).min(), s.rolling(3).max())
print(s.rolling(3).median())
print(s.rolling(3).std())
print(s.rolling(3).var())
print(s.rolling(3).count())
print(s.rolling(3, min_periods=1).mean())
print(s.rolling(4, min_periods=2).sum())
print(s.rolling(3, center=True).mean())
print(s.rolling(3).apply(lambda w: w.max() - w.min()))
print(s.rolling(3).apply(lambda w: w.sum(), raw=True))
print(s.rolling(2).agg(['mean', 'max']))
n = pd.Series([1.0, None, 3.0, 4.0, None, 6.0])
print(n.rolling(2).sum())
print(n.rolling(2, min_periods=1).mean())
print(n.rolling(3, min_periods=2).std())
print(s.expanding().sum())
print(s.expanding().mean())
print(s.expanding(min_periods=3).max())
print(s.expanding().std())
print(pd.Series([1, 2, 3, 4]).rolling(2).sum())
rng = np.random.default_rng(1)
r = pd.Series(rng.normal(size=40))
print(r.rolling(5).mean().tolist()[4:9])
print(r.rolling(7).std().tolist()[6:10])
print(r.rolling(6).sum().tolist()[5:9])
print(r.expanding().var().tolist()[1:4])
big = pd.Series(np.arange(10000.0) * 0.1)
print(big.rolling(50).mean().iloc[-1], big.rolling(50).sum().iloc[-1], big.rolling(50).var().iloc[-1])
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [0.5, 1.5, 2.5, 3.5]})
print(df.rolling(2).mean())
print(df.rolling(2).sum())
print(df.expanding().sum())
print(df.rolling(2).agg(['sum', 'min']))
# rank
v = pd.Series([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
print(v.rank())
print(v.rank(method='min'), v.rank(method='max'), v.rank(method='first'), v.rank(method='dense'))
print(v.rank(ascending=False))
print(v.rank(pct=True))
w = pd.Series([2.5, None, 1.0, 2.5])
print(w.rank(), w.rank(na_option='bottom'), w.rank(na_option='top'))
print(pd.Series(['b', 'a', 'c', 'a']).rank())
print(pd.DataFrame({'x': [3, 1, 2], 'y': [1.5, 1.5, 0.5]}).rank())
print(pd.DataFrame({'x': [3, 1, 2], 'y': [1.5, 1.5, 0.5]}).rank(method='min', ascending=False))
print(v.groupby(v % 2).rank() if False else 'skip')
