import numpy as np
import pandas as pd

s = pd.Series([1.0, 2.0, 4.0, 7.0, 11.0, 16.0])
print(s.ewm(span=3).mean())
print(s.ewm(com=0.5).mean())
print(s.ewm(alpha=0.3).mean())
print(s.ewm(halflife=2).mean())
print(s.ewm(span=3, adjust=False).mean())
print(s.ewm(alpha=0.3, adjust=False).mean())
print(s.ewm(span=4, min_periods=3).mean())
print(s.ewm(span=3).std())
print(s.ewm(span=3).var())
print(s.ewm(span=3).var(bias=True))
print(s.ewm(span=3, adjust=False).var())
n = pd.Series([1.0, None, 3.0, 4.0, None, 6.0])
print(n.ewm(span=3).mean())
print(n.ewm(span=3, ignore_na=True).mean())
print(n.ewm(span=4, adjust=False).mean())
print(n.ewm(span=3, adjust=False, ignore_na=True).mean())
print(n.ewm(span=3).std())
rng = np.random.default_rng(3)
r = pd.Series(rng.normal(size=50))
print(r.ewm(span=10).mean().tolist()[8:12])
print(r.ewm(alpha=0.2, adjust=False).mean().tolist()[8:12])
print(r.ewm(halflife=5).std().tolist()[8:12])
print(r.ewm(com=3).var().tolist()[8:12])
df = pd.DataFrame({'a': [1.0, 2.0, 3.0, 4.0], 'b': [4, 3, 2, 1]})
print(df.ewm(span=2).mean())
print(df.ewm(alpha=0.5).std())
try:
    s.ewm(span=3, alpha=0.5)
except ValueError as e:
    print('ValueError')
