import io
import numpy as np
import pandas as pd

df = pd.DataFrame({'a': [1, 2], 'b': [0.1 + 0.2, 1 / 3], 'c': ['x/y', 'é"q\n'], 'd': [True, None], 'e': [1e-11, 1e20]}, index=['r1', 'r2'])
print(df.to_json())
print(df.to_json(orient='records'))
print(df.to_json(orient='index'))
print(df.to_json(orient='split'))
print(df.to_json(orient='values'))
print(df.to_json(orient='records', lines=True))
print(df.to_json(orient='columns', indent=2))
print(df.to_json(orient='records', indent=1))
print(df['b'].to_json(), df['a'].to_json(orient='split'), pd.Series([1, None, 3.5]).to_json())
print(pd.Series([1, 2], name='n').to_json(orient='records'))
print(pd.DataFrame({'a': [1.5, 2.0, np.nan, np.inf]}).to_json())
print(pd.DataFrame({'a': [123456789.123456789, 0.000001234, -2.5, 0.99999999999]}).to_json())
print(pd.DataFrame({'a': [1, 2]}).to_json(double_precision=3), pd.DataFrame({'a': [1.23456, 2, 0.005, 0.995]}).to_json(double_precision=2))
print(pd.DataFrame({'a': [1.5]}, index=[10]).to_json(), pd.DataFrame({'a': [1.5]}, index=[0.5]).to_json())
print(pd.DataFrame({'a': []}).to_json(), pd.DataFrame().to_json(orient='records'))
print(pd.DataFrame({'a': ['\t\r\b\f\\ \u0001 😀']}).to_json())
print(pd.DataFrame({'a': ['é']}).to_json(force_ascii=False))
J = lambda s, **k: pd.read_json(io.StringIO(s), **k)
print(J('{"a":{"0":1,"1":2},"b":{"0":"x","1":null}}'))
print(J('[{"a":1,"b":"x"},{"a":2,"b":null}]'))
print(J('{"a":{"r1":1,"r2":2}}'))
print(J('{"index":["r1","r2"],"columns":["a"],"data":[[1],[2]]}', orient='split'))
print(J('[[1,2],[3,4]]', orient='values'))
print(J('{"a":1.5,"b":2.5}', typ='series'))
print(J('{"a":1,"b":2}\n{"a":3,"b":4}\n', lines=True))
print(J('{"a":{"0":1.5,"1":2}}').dtypes.tolist(), J('{"a":{"0":true,"1":false}}').dtypes.tolist(), J('{"a":{"0":"2020","1":"x"}}').dtypes.tolist())
print(J('{"a":{"b":1}}').index.tolist(), J('{"a":{"10":1,"20":2}}').index.tolist(), J('{"a":{"10":1,"20":2}}').index)
print(J('[{"a":1},{"a":2}]', orient='records').index)
print(J('{"a":{"1":1,"0":2}}'))
print(J('{"a":{"0":1,"1":null}}').dtypes.tolist(), J('{"a":{"0":null,"1":null}}').dtypes.tolist())
print(J('[{"a":1,"b":2},{"a":3}]'))
print(J('{"x":[1,2,3]}'))
print(J('{"a":{"0":10000000000}}').dtypes.tolist(), J('{"a":{"0":1.0,"1":2.0}}').dtypes.tolist())
print(J('{"r1":1,"r2":2}', typ='series'), J('[1.5,2.5]', typ='series'))
print(J(df.to_json(orient='split'), orient='split'))
print(J(df[['a', 'b']].to_json()).equals(df[['a', 'b']]), J(df[['a', 'b']].to_json(orient='records'), orient='records').shape)
print(J(df.to_json(orient='index'), orient='index'))
