import numpy as np
import pandas as pd

x = pd.Series([1, 7, 5, 4, 6, 3])
print(pd.cut(x, 3))
print(pd.cut(x, 3).cat.categories)
print(pd.cut(x, [0, 2, 5, 10]))
print(pd.cut(x, [0, 2, 5, 10], labels=['lo', 'mid', 'hi']))
print(pd.cut(x, [0, 2, 5, 10], labels=False))
print(pd.cut(x, [0, 2, 5, 10], right=False))
print(pd.cut(x, [1, 3, 5, 7], include_lowest=True))
print(pd.cut(x, [1.5, 3.25, 7.5]))
print(pd.cut(x, 4, precision=1))
print(pd.cut([1, 5, 10], 2))
print(pd.cut(pd.Series([0.1, 0.5, 0.9, 1.3]), 3))
print(pd.cut(x, [0, 3, 8], retbins=True)[1])
print(pd.qcut(x, 3))
print(pd.qcut(x, [0, 0.5, 1.0]))
print(pd.qcut(x, 2, labels=['a', 'b']))
print(pd.qcut(pd.Series(range(10)), 4))
print(pd.qcut(pd.Series([0.1234567, 0.55555, 0.9, 1.3, 2.71828, 3.14159]), 3))
print(pd.qcut(x, 3, labels=False))
print(pd.cut(x, [0, 2, 5, 10]).value_counts())
print(pd.cut(x, [0, 2, 5, 10]).value_counts(sort=False))
print(pd.cut(x, [2, 5]))
print(pd.cut(x, [0, 2, 5, 10]).dtype, pd.cut(x, [0, 2, 5, 10]).cat.ordered)
print(x.groupby(pd.cut(x, [0, 2, 5, 10])).sum())
print(x.groupby(pd.cut(x, [0, 2, 5, 10]), observed=False).count())
d = pd.DataFrame({'a': x, 'bin': pd.cut(x, [0, 3, 10])})
print(d)
print(d.groupby('bin').a.agg(['count', 'mean']))
print(d['bin'].value_counts())
iv = pd.cut(x, [0, 2, 5, 10])[0]
print(iv, type(iv).__name__)
print(iv.left, iv.right, iv.closed, iv.mid, iv.length, 1 in iv, 3 in iv, repr(iv))
print(pd.cut(x, [0, 2, 5, 10]).cat.categories.tolist())
print(pd.cut(x, [0, 2, 5, 10], duplicates='drop').dtype)
try:
    pd.cut(x, [0, 2, 2, 10])
except ValueError as e:
    print('ValueError', e)
print(pd.cut(x, [0, 2, 2, 10], duplicates='drop').cat.categories)
try:
    pd.qcut([1, 1, 1, 1], 3)
except ValueError as e:
    print('ValueError', str(e)[:60])
print(pd.cut(np.array([1.0, 2.0, np.nan, 4.0]), [0, 2, 5]))
ages = pd.Series([5, 17, 18, 35, 64, 65, 90])
groups = pd.cut(ages, [0, 17, 64, 120], labels=['child', 'adult', 'senior'])
print(groups)
print(groups.value_counts())
print(pd.DataFrame({'age': ages, 'grp': groups}).groupby('grp', observed=False)['age'].agg(['min', 'max', 'mean']))
print(pd.qcut(pd.Series(np.arange(100.0)), 5).value_counts())
print(pd.qcut(pd.Series(np.arange(12)), [0, 0.25, 0.75, 1], labels=['low', 'mid', 'high']).tolist())
