import numpy as np
import pandas as pd

sizes = pd.CategoricalDtype(['S', 'M', 'L', 'XL'], ordered=True)
df = pd.DataFrame({
    'size': pd.Series(['M', 'L', 'S', 'M', 'XL', 'S', 'M'], dtype=sizes),
    'color': pd.Series(['r', 'g', 'r', 'b', 'g', 'r', 'g'], dtype='category'),
    'qty': [3, 5, 2, 8, 1, 4, 6],
    'price': [9.5, 20.0, 5.25, 9.5, 99.0, 5.25, 9.5],
})
print(df)
print(df.dtypes)
print(df['size'].cat.categories.tolist(), df['size'].cat.ordered, df['size'].dtype == sizes)
print(df.sort_values('size'))
print(df.sort_values(['size', 'qty'], ascending=[False, True])['qty'].tolist())
print(df[df['size'] >= 'L'])
print(df['size'].max(), df['size'].min(), (df['size'] > 'M').sum())
print(df.groupby('size', observed=False)['qty'].sum())
print(df.groupby('size', observed=True)['qty'].sum())
print(df.groupby(['size', 'color'], observed=False)['qty'].sum().head(8))
print(df.groupby(['size', 'color'], observed=True)['qty'].sum())
print(df.groupby('color')['price'].mean())
print(df.groupby('color', observed=False).agg(total=('qty', 'sum'), n=('qty', 'count')))
print(df['color'].value_counts())
print(pd.crosstab(df['size'], df['color']))
print(df.pivot_table(index='size', columns='color', values='qty', aggfunc='sum', observed=False))
print(df['size'].astype(str).tolist())
print(df.assign(code=df['size'].cat.codes)[['size', 'code']].head(3))
print(df['color'].cat.rename_categories({'r': 'red', 'g': 'green', 'b': 'blue'}).value_counts())
print(df['size'].cat.reorder_categories(['XL', 'L', 'M', 'S']).sort_values().tolist())
print(df['size'].isin(['S', 'M']).sum(), df['size'].eq('M').sum(), df['size'].ne('M').sum())
print(df['size'] == df['size'])
print(pd.Series(pd.Categorical(['a', 'zz'], categories=['a', 'b'])).tolist())
print(pd.Series(pd.Categorical([3, 1, 2, 1])).cat.categories.tolist(), pd.Series(pd.Categorical([3, 1, 2, 1])).value_counts().tolist())
print(pd.Series(pd.Categorical([1.5, 1.5, 2.5])).value_counts())
n = pd.Series(pd.Categorical(['b', None, 'a'], ordered=True))
print(n.min(), n.max(), n.sort_values().tolist(), n.isna().tolist(), n.dropna().tolist())
print(n.where(n.notna(), 'a').tolist() if False else n.fillna('a').tolist())
print(pd.get_dummies(df[['size', 'qty']]).columns.tolist())
print(df['size'].describe())
t = pd.DataFrame({'k': pd.Categorical(['a', 'b'], categories=['a', 'b', 'c']), 'v': [1, 2]}).set_index('k')
print(t)
print(t.index.tolist(), t.loc['b', 'v'], t.reindex(['a', 'c']).shape if False else 'noreindex')
print(t.sort_index(ascending=False))
print(pd.concat([df['size'], df['size']], ignore_index=True).dtype)
print(df['size'].cat.codes.tolist(), df['size'].cat.codes.dtype)
print(df.iloc[[0, 3], :]['size'])
print(df['color'].unique(), df['size'].unique())
print(df['color'].cat.set_categories(['r', 'g']).isna().sum())
x = df['price']
print(pd.cut(x, [0, 10, 50, 100], labels=['cheap', 'mid', 'dear']).value_counts().to_dict())
print(pd.qcut(df['qty'], 3, labels=['lo', 'mid', 'hi']).tolist())
print(df.assign(band=pd.cut(df['price'], [0, 10, 100]))['band'].value_counts())
print(df.groupby(pd.cut(df['price'], [0, 10, 100]), observed=True)['qty'].sum())
print(df['size'].to_frame().T.shape)
