import numpy as np
import pandas as pd

s = pd.Series(pd.date_range('2020-01-30 08:15', periods=5, freq='17h'))
print(s)
print(s.dtype)
print(s.dt.year.dtype, s.dt.dayofweek.dtype)
print(s.dt.year.tolist(), s.dt.month.tolist(), s.dt.day.tolist())
print(s.dt.hour.tolist(), s.dt.minute.tolist())
print(s.dt.dayofweek.tolist(), s.dt.dayofyear.tolist(), s.dt.quarter.tolist())
print(s.dt.is_month_end.tolist(), s.dt.is_month_start.tolist())
print(s.dt.day_name().tolist())
print(s.dt.month_name().tolist())
print(s.dt.date.tolist())
print(s.dt.time.tolist())
print(s.dt.strftime('%Y/%m/%d %H:%M'))
print(s.dt.floor('D'))
print(s.dt.ceil('h'))
print(s.dt.round('h'))
print(s.dt.normalize())
print(s.dt.isocalendar())
print(s.diff())
print(s - s.iloc[0])
print((s - s.iloc[0]).dt.days.tolist())
print((s - s.iloc[0]).dt.total_seconds().tolist())
print((s - s.iloc[0]).dt.seconds.tolist())
print(s + pd.Timedelta(days=1))
print(s - pd.Timedelta(hours=8))
print(s + pd.DateOffset(months=1))
print(s + pd.offsets.MonthEnd())
print(s > '2020-01-31')
print(s == pd.Timestamp('2020-01-30 08:15'))
print(s.min(), s.max())
print(s.mean())
print(s.sort_values(ascending=False))
print(s.astype('int64').tolist())
print(s.astype(str).tolist())
print(s.astype('datetime64[ns]'))
print(s.astype('datetime64[s]').dtype)
print(s.idxmax(), s.idxmin())
print(s.nunique(), s.count())
print(s.shift(1))
print(s.head(2))
print(s.iloc[0], type(s.iloc[0]).__name__)
print(s.isna().tolist())
print(s.describe())

t = pd.Series(pd.to_timedelta(['1 days', '2 days 03:00:00', '36h', None]))
print(t)
print(t.dtype)
print(t.dt.days.tolist() if False else t.dt.total_seconds().tolist())
print(t.sum(), t.mean(), t.max(), t.min())
print(t * 2)
print(t / pd.Timedelta(hours=1))
print(t.dt.floor('D'))
print(t.dt.components if False else '')
print(t.isna().tolist())
print(t.sort_values())

p = pd.Series(['2020-01-01', '2020-06-15', None, '2021-12-31'])
d = pd.to_datetime(p)
print(d)
print(d.dt.year.tolist())
print(d.dt.year)
print(d.dt.is_leap_year.tolist())
print(d.fillna(pd.Timestamp('1999-01-01')))
print(d.dropna().tolist())
print(d.isna().tolist())
print((d - pd.Timestamp('2020-01-01')).tolist())
print(d.max() - d.min())

df = pd.DataFrame({'when': pd.date_range('2020-01-01', periods=4, freq='MS'), 'v': [1.5, 2.5, 3.5, 4.5]})
print(df)
print(df.dtypes)
print(df['when'].dt.month.tolist())
print(df[df['when'] > '2020-02-15'])
print(df.sort_values('when', ascending=False))
print(df.set_index('when'))
df['next'] = df['when'] + pd.Timedelta(days=10)
df['gap'] = df['next'] - df['when']
print(df)
print(df.describe())
df.info()
print(df.agg({'when': ['min', 'max']}))
print(df['when'].diff().tolist())
print(df.iloc[1])
print(df.loc[0, 'when'])
