import datetime
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'when': pd.to_datetime(['2020-01-15', '2020-01-20', '2020-02-03', '2020-02-10', '2020-03-01', '2020-03-15']),
    'who': list('ababab'),
    'amt': [10, 20, 30, 40, 50, 60],
})
print(df.groupby(df['when'].dt.month)['amt'].sum())
print(df.groupby(df['when'].dt.year)['amt'].agg(['sum', 'count']))
print(df.groupby('when')['amt'].sum().head(3))
print(df.groupby('who')['when'].min())
print(df.groupby('who')['when'].max())
print(df.groupby('who')['when'].agg(['min', 'max']))
print(df.groupby('who').agg(first=('when', 'first'), total=('amt', 'sum')))
print(df.pivot_table(index=df['when'].dt.month, columns='who', values='amt', aggfunc='sum'))
print(df.assign(month=df['when'].dt.month_name()).head(3))
df['year'] = df['when'].dt.year
df['dow'] = df['when'].dt.dayofweek
print(df)
df.loc[df['amt'] > 50, 'when'] = pd.Timestamp('1999-12-31')
print(df['when'].tolist()[-1], df['when'].dtype)
df.loc[0, 'when'] = pd.Timestamp('2001-01-01 10:00')
print(df['when'].head(2))
df.loc[1, 'when'] = pd.NaT
print(df['when'].isna().tolist())
df['when'] = df['when'].fillna(pd.Timestamp('1970-01-01'))
print(df['when'].head(3))
print(df['when'].between('2001-01-01', '2020-02-05').tolist())
print(df['when'].isin([pd.Timestamp('2020-02-03'), pd.Timestamp('1970-01-01')]).tolist())
print(df['when'].unique())
print(df['when'].value_counts().head(2))
print(df.sort_values('when')['amt'].tolist())
print(df['when'].nlargest(2).tolist())
print(df['when'].rank().tolist())
print(df['when'].clip(lower=pd.Timestamp('2000-01-01')).tolist()[:2])
print(df['when'].where(df['amt'] > 20).tolist()[:4])
print(df['when'].duplicated().tolist())
print(df['when'].argmax(), df['when'].argmin())
print(df['when'].to_frame().T.shape)
print(df['when'].map(lambda t: t.strftime('%y')).tolist())
print(df['when'].apply(lambda t: t.year).tolist())
print(df['when'].astype('string').tolist() if False else '')
print(list(df['when'])[:2])
print(df['when'].dt.date.nunique())
print(df['when'].max() - df['when'].min())
print((df['when'] - df['when'].shift(1)).tolist()[:3])
print((df['when'] - pd.Timestamp('2020-01-01')).dt.days.tolist())
print(df['when'].diff().dt.days.tolist())
td = pd.to_timedelta([90, 30, 150], unit='m')
print(td)
print(pd.Series(td).cumsum())
print(pd.Series(td).sum(), pd.Series(td).median())
print(pd.Series(td).dt.total_seconds() / 3600)
print(pd.Series(td).abs().tolist())
print(td.total_seconds())
print(td.days, td.seconds)
print(td.sum() if hasattr(td, 'sum') else '')
print(datetime.datetime(2020, 1, 1) + pd.Timedelta(days=1))
print(pd.Timestamp('2020-01-02') - datetime.datetime(2020, 1, 1))
print(pd.Timestamp('2020-01-02') > datetime.datetime(2020, 1, 1))
print(pd.Timedelta(days=1) == datetime.timedelta(days=1))
print(pd.Timestamp('2020-01-01') + datetime.timedelta(hours=5))
print(pd.Series([datetime.datetime(2020, 1, 1), datetime.datetime(2020, 1, 2, 3, 4)]))
print(pd.Series([datetime.date(2020, 1, 1)]).dtype)
print(pd.DataFrame({'a': pd.date_range('2020-01-01', periods=3)}).shift(1))
print(pd.DataFrame({'a': pd.date_range('2020-01-01', periods=3)}).diff())
print(pd.DataFrame({'a': pd.date_range('2020-01-01', periods=3)}).max())
print(pd.DataFrame({'a': pd.date_range('2020-01-01', periods=3), 'b': [1, 2, 3]}).T)
print(pd.DataFrame({'a': pd.date_range('2020-01-01', periods=3), 'b': [1, 2, 3]}).sum(numeric_only=True))
print(pd.Series(pd.date_range('2020-01-01', periods=3)).to_numpy().dtype if False else '')
s = pd.Series([1, 2, 3], index=pd.to_datetime(['2020-03-01', '2020-01-01', '2020-02-01']))
print(s.sort_index())
print(s.index.is_monotonic_increasing)
try:
    print(s.loc['2020-01-15':'2020-02-15'])
except KeyError as e:
    print('KeyError', e)
print(s.index.sort_values())
print(s.index.argsort().tolist() if hasattr(s.index, 'argsort') else '')
print(s.idxmax(), s.idxmin())
print(s.index.month.tolist())
print(s.rename_axis('d').reset_index())
print(s.groupby(s.index.year).sum())
print(pd.Series(range(3), index=pd.period_range('2020-01', periods=3, freq='M')) if False else '')
print(pd.Timestamp('2020-02-29') + pd.DateOffset(years=1))
print(pd.Timestamp('2020-03-31') - pd.DateOffset(months=1))
print(pd.Timestamp('2020-03-31') + pd.offsets.QuarterEnd())
print(pd.Timestamp('2020-03-31') + pd.offsets.YearEnd())
print(pd.Timestamp('2020-03-15') + pd.offsets.Week(2))
print(pd.Timestamp('2020-03-15') + pd.offsets.Hour(5))
print(pd.Timestamp('2020-03-14') + pd.offsets.BDay(1))
print(pd.Timestamp('2020-03-14') - pd.offsets.BDay(1))
print(pd.Timestamp('2020-03-14').normalize() + pd.DateOffset(days=3, hours=2))
print(pd.date_range('2020-01-31', periods=3, freq=pd.offsets.MonthEnd()))
print(pd.date_range('2020-01-01', periods=3, freq=pd.DateOffset(months=1)))
print(pd.date_range('2020-01-01', periods=3, freq=pd.Timedelta(hours=6)))
