import numpy as np
import pandas as pd

idx = pd.date_range('2020-01-01', periods=10, freq='D')
s = pd.Series(np.arange(10), index=idx)
print(s.resample('3D').sum())
print(s.resample('3D').mean())
print(s.resample('W').sum())
print(s.resample('W-MON').sum())
print(s.resample('ME').sum())
print(s.resample('MS').count())
print(s.resample('2D').first())
print(s.resample('2D').last())
print(s.resample('5D').max())
print(s.resample('5D').agg(['min', 'max', 'sum']))
print(s.resample('5D').ohlc())
print(s.resample('4D').size())
print(s.resample('12h').asfreq().head(5))
print(s.resample('12h').ffill().head(5))
print(s.resample('12h').bfill().head(5))
print(s.resample('QE').sum())
print(s.resample('YE').sum())
print(s.resample('3D', closed='right', label='right').sum())
print(s.resample('3D').apply(lambda x: x.max() - x.min()))

h = pd.Series(np.arange(1, 9) * 1.5, index=pd.date_range('2020-03-01 22:00', periods=8, freq='h'))
print(h)
print(h.resample('D').sum())
print(h.resample('3h').mean())
print(h.resample('90min').sum())
print(h.resample('2h').agg({'v': 'sum'}) if False else '')

gap = pd.Series([1.0, 2.0, 3.0], index=pd.to_datetime(['2020-01-01', '2020-01-04', '2020-01-05']))
print(gap.resample('D').sum())
print(gap.resample('D').mean())
print(gap.resample('D').count())
print(gap.resample('D').asfreq())
print(gap.resample('D').ffill())

df = pd.DataFrame({'a': np.arange(8), 'b': np.arange(8) * 2.5, 'k': list('xyxyxyxy')},
                  index=pd.date_range('2021-05-01', periods=8, freq='12h'))
print(df.resample('D').sum(numeric_only=True))
print(df[['a', 'b']].resample('D').mean())
print(df[['a', 'b']].resample('D').agg({'a': 'sum', 'b': 'max'}))
print(df[['a', 'b']].resample('2D').agg(['sum', 'mean']))
print(df['a'].resample('D').sum())

df2 = pd.DataFrame({'when': pd.date_range('2021-01-31', periods=6, freq='10D'), 'v': np.arange(6), 'g': list('aabbab')})
print(df2.resample('ME', on='when').sum(numeric_only=True))
print(df2.resample('ME', on='when')['v'].sum())
print(df2.groupby(pd.Grouper(key='when', freq='ME')).sum(numeric_only=True))
print(df2.groupby(pd.Grouper(key='when', freq='ME'))['v'].count())
print(df2.groupby([pd.Grouper(key='when', freq='ME'), 'g'])['v'].sum())
print(df2.set_index('when').groupby(pd.Grouper(freq='ME'))['v'].sum())
print(df2.groupby(df2['when'].dt.month)['v'].sum())
print(df2.groupby(df2['when'].dt.to_period('M') if False else df2['when'].dt.year)['v'].sum())
print(df2.set_index('when').resample('W').mean(numeric_only=True))
print(df2.set_index('when')['v'].resample('15D').sum())
print(df2.set_index('when')['v'].cumsum().resample('ME').last())
print(df2.set_index('when').asfreq('10D'))
print(df2.set_index('when')['v'].asfreq('5D'))
print(df2.set_index('when')['v'].asfreq('5D', method='ffill'))
