import datetime
import pandas as pd

t = pd.Timestamp('2020-03-15 10:30:45.123456')
print(t)
print(repr(t))
print(t.year, t.month, t.day, t.hour, t.minute, t.second, t.microsecond)
print(t.dayofweek, t.dayofyear, t.quarter, t.week, t.days_in_month, t.is_leap_year)
print(t.day_name(), t.month_name())
print(t.is_month_start, t.is_month_end, t.is_quarter_end, t.is_year_start)
print(t.strftime('%Y-%m-%d %H:%M'))
print(t.isoformat())
print(t.normalize())
print(t.floor('h'), t.ceil('h'), t.round('15min'))
print(t.date(), t.time())
print(t + pd.Timedelta(days=2, hours=3))
print(t - pd.Timedelta('1 days 06:00:00'))
print(t - pd.Timestamp('2020-01-01'))
print(pd.Timestamp(2021, 5, 17))
print(pd.Timestamp(2021, 5, 17, 8, 15))
print(pd.Timestamp('2020-01-31') + pd.DateOffset(months=1))
print(pd.Timestamp('2020-01-31') + pd.offsets.MonthEnd())
print(pd.Timestamp('2020-01-15') + pd.offsets.MonthEnd())
print(pd.Timestamp('2020-01-15') + pd.offsets.MonthBegin())
print(pd.Timestamp('2020-01-03') + pd.offsets.BDay(3))
print(pd.Timestamp('2020-01-01') + 3 * pd.offsets.Day())
print(t > pd.Timestamp('2020-01-01'), t == pd.Timestamp('2020-03-15 10:30:45.123456'))
print(t.replace(year=1999, hour=0))
print(pd.Timestamp('2020-01-01').timestamp())
print(pd.Timestamp(datetime.datetime(2020, 5, 6, 7, 8, 9)))
print(t.to_pydatetime())
print(pd.Timestamp('2020-01-01').unit, pd.Timestamp('2020-01-01 00:00:00.123456789').unit)

d = pd.Timedelta(days=1, hours=2, minutes=3, seconds=4, milliseconds=5)
print(d)
print(repr(d))
print(d.days, d.seconds, d.microseconds, d.total_seconds())
print(pd.Timedelta('2 days'), pd.Timedelta('1h30m'), pd.Timedelta('0.5s'))
print(pd.Timedelta(5, unit='m'), pd.Timedelta(1.5, unit='h'))
print(d * 2, d / 2, d // pd.Timedelta(hours=1), d / pd.Timedelta(hours=1))
print(d + d, d - pd.Timedelta(hours=1), -d, abs(-d))
print(d > pd.Timedelta(days=1), d == pd.Timedelta(days=1, hours=2, minutes=3, seconds=4, milliseconds=5))
print(d.floor('h'), d.ceil('h'), d.round('min'))
print(pd.Timedelta(days=-1, hours=3))
print(pd.NaT, pd.isna(pd.NaT), pd.NaT == pd.NaT)
print(pd.Timestamp('2020-01-01') + pd.NaT)
print(pd.isna(pd.Timestamp('2020-01-01')))
print(pd.Timedelta(0), pd.Timedelta(seconds=90))
print(repr(pd.offsets.Day()), repr(3 * pd.offsets.Hour()))
print(pd.offsets.MonthEnd().freqstr, pd.DateOffset(months=2).freqstr if False else '')
