import numpy as np
import pandas as pd

m = pd.period_range('2021-01', periods=14, freq='M')
s = pd.Series(np.arange(14.0), index=m)
print(s.head(3))
print(s['2021'])
print(s['2022'].sum())
print(s['2021-11':'2022-02'])
print(s.loc['2021-06'])
print(s.index.min(), s.index.max(), s.index.is_monotonic_increasing)
print(s.groupby(s.index.year).sum())
print(s.groupby(s.index.quarter).mean())
print(s.index.asfreq('Q'))
print(s.index.asfreq('Y'))
print(s.index.shift(2)[:3])
print(m[:3].to_timestamp().freq, m[:3].to_timestamp(how='end'))
print(s.to_timestamp().head(3))
print(s.resample('QE').sum() if False else '')
q = pd.period_range('2020Q1', periods=6, freq='Q')
print(q)
print(q.start_time, q.end_time)
print(pd.Series(q).dt.quarter.tolist(), pd.Series(q).dt.qyear.tolist())
fy = pd.period_range('2020Q1', periods=4, freq='Q-MAR')
print(fy)
print(fy.start_time)
w = pd.period_range('2020-03-02', periods=4, freq='W')
print(w)
print(w.start_time, w.end_time)
h = pd.period_range('2020-03-01 22:00', periods=4, freq='h')
print(h)
print(pd.Series(h).dt.hour.tolist(), pd.Series(h).dt.day.tolist())
print(pd.Series(pd.period_range('2020-01', periods=3, freq='M')).dt.asfreq('D'))
print(pd.Series(pd.period_range('2020-01', periods=3, freq='M')).dt.asfreq('D', 'start'))
dt = pd.date_range('2021-01-15', periods=6, freq='45D')
print(dt.to_period('M'))
print(pd.Series(range(6), index=dt).to_period('M'))
print(pd.DataFrame({'a': range(6)}, index=dt).to_period('Q'))
print(pd.DataFrame({'when': dt, 'v': range(6)}).assign(per=lambda d: d['when'].dt.to_period('M')))
df = pd.DataFrame({'when': dt, 'v': range(6)})
df['mon'] = df['when'].dt.to_period('M')
print(df.groupby('mon')['v'].sum())
print(df.groupby('mon').size())
print(df['mon'].value_counts().sort_index())
print(df.sort_values('mon', ascending=False).head(3))
print(df['mon'].astype(str).tolist())
print(df['mon'].dt.to_timestamp().tolist()[:2])
print(df['mon'].astype('period[Q]').tolist()[:2])
print(df['mon'] + 1)
print((df['mon'] - df['mon'].iloc[0]).tolist())
print(df['mon'].diff().tolist())
print(df.set_index('mon').head(3))
print(df['mon'].unique())
print(df['mon'].isin([pd.Period('2021-01', 'M')]).tolist())
print(df['mon'].nunique(), df['mon'].min(), df['mon'].max())
print(df['mon'].dt.strftime('%b-%Y').tolist())
print(df['mon'].dt.year.tolist(), df['mon'].dt.month.tolist(), df['mon'].dt.days_in_month.tolist())
print(df.dtypes)
print(df.describe(include='all') if False else '')
print(pd.Period('2020-02-29', 'D') + 365, pd.Period('2020', 'Y') + 1, pd.Period('2020Q4') + 1)
print(pd.Period('2020-03', 'M') in pd.period_range('2020-01', periods=4, freq='M'))
print(pd.PeriodIndex(['2020-01', '2020-02'], freq='M').to_timestamp())
print(pd.PeriodIndex(pd.date_range('2020-01-01', periods=3, freq='MS'), freq='M') if False else '')
try:
    pd.period_range('2020-01', periods=3, freq='M') + pd.period_range('2020-01', periods=3, freq='M')
except Exception as e:
    print(type(e).__name__)
try:
    pd.Series(m) > pd.Period('2020-01-01', 'D')
except Exception as e:
    print(type(e).__name__, e)
