import pandas as pd
import numpy as np

for f in ['Y', 'Q', 'M', 'W', 'D', 'h', 'min', 's', 'Q-MAR', 'Y-JUN', 'W-MON', 'ms']:
    p = pd.Period('2020-03-18 10:20:30.123', freq=f)
    print(f, repr(p), str(p), p.ordinal, p.freqstr, p.start_time, p.end_time)
print(pd.Period('2020-03', 'M') + 2, pd.Period('2020-03', 'M') - pd.Period('2019-12', 'M'))
print(pd.Period('2020-03', 'M') < pd.Period('2020-04', 'M'), pd.Period('2020-03', 'M') == pd.Period('2020-03', 'M'))
print(pd.Period('2020Q2'), pd.Period('2020-W10') if False else '', pd.Period(2020, freq='Y'), pd.Period('2020-03-05', 'D'))
p = pd.Period('2020-03-18', 'D')
print(p.year, p.month, p.day, p.quarter, p.dayofweek, p.dayofyear, p.days_in_month, p.week, p.is_leap_year, p.weekday)
print(p.asfreq('M'), p.asfreq('Y'), pd.Period('2020-03', 'M').asfreq('D', 'end'), pd.Period('2020-03', 'M').asfreq('D', 'start'))
print(p.to_timestamp(), pd.Period('2020-03', 'M').to_timestamp(how='end'), p.strftime('%Y/%m/%d %a'))
print(pd.Period('2020-03', 'M').qyear, pd.Period('2020Q1').start_time, pd.Period('2020Q1').end_time)
r = pd.period_range('2020-01', periods=5, freq='M')
print(r)
print(repr(r))
print(r.dtype, r.freq, r.freqstr)
print(r.year, r.month, r[0], r[-1], r[1:3])
print(pd.period_range('2020-01-01', '2020-01-05', freq='D'))
print(pd.period_range('2019Q4', periods=3, freq='Q'))
s = pd.Series(range(5), index=r)
print(s)
print(s['2020-02':'2020-04'])
print(s['2020-03'])
print(r.to_timestamp())
print(r.to_timestamp(how='end'))
print(r + 1, r - 2)
print(r.asfreq('Y'), r.asfreq('D', how='end'))
d = pd.Series(pd.date_range('2020-01-15', periods=5, freq='20D'))
print(d.dt.to_period('M'))
print(d.dt.to_period('M').dtype)
print(d.dt.to_period('W'))
print(d.dt.to_period('Q'))
print(d.dt.to_period('Y'))
print(d.dt.to_period('D').tolist())
pdx = pd.date_range('2020-01-15', periods=4, freq='20D').to_period('M')
print(pdx)
pm = d.dt.to_period('M')
print(pm.dt.year.tolist(), pm.dt.month.tolist(), pm.dt.start_time.tolist(), pm.dt.end_time.tolist())
print(pm.dt.to_timestamp())
print(pm.value_counts())
print(pm.astype(str).tolist())
print(pm.min(), pm.max())
print(pm.sort_values(ascending=False).tolist())
print(pm.iloc[0], type(pm.iloc[0]).__name__)
print(pm == pd.Period('2020-02', 'M'))
print(pm > pd.Period('2020-02', 'M'))
print(pm - pd.Period('2020-01', 'M'))
print(pm + 1)
print(pm.diff())
df = pd.DataFrame({'m': pm, 'v': [1, 2, 3, 4, 5]})
print(df)
print(df.dtypes)
print(df.groupby('m')['v'].sum())
print(df.set_index('m'))
print(pd.PeriodIndex(['2020-01', '2020-03'], freq='M'))
print(pd.PeriodIndex(['2020-01-05', '2020-03-09'], freq='D'))
print(pd.Series([pd.Period('2020-01', 'M'), pd.Period('2020-05', 'M')]))
print(pd.Period('2020-01', 'M').strftime('%b %Y'))
print(pd.Timestamp('2020-03-18').to_period('M'), pd.Timestamp('2020-03-18').to_period('W'))
print(df['m'].dt.strftime('%Y-%m').tolist())
print(pd.Period('NaT') if False else pd.NaT)
print(pd.Series(pd.to_datetime(['2020-01-05', None])).dt.to_period('M'))
print(s.index.to_timestamp().dtype)
print(s.resample('Q').sum() if False else '')
print(s.to_timestamp())
x = pd.Series(range(6), index=pd.date_range('2020-01-15', periods=6, freq='20D'))
print(x.to_period('M'))
print(x.to_period('M').groupby(level=0).sum())
print(r.is_monotonic_increasing, r.min(), r.max())
print(r.strftime('%m/%Y'))
print(r.astype(str))
print(r.get_loc('2020-03'))
print(pd.Period('2020-01', 'M') in r, r.isin([pd.Period('2020-02', 'M')]))
print(pd.Period('2020-03', freq='M').days_in_month, pd.Period('2020-02', freq='M').end_time.day)
print(pd.Period('2020-03', 'M').ordinal, pd.Period('1969-12', 'M').ordinal, pd.Period('2020-03-02', 'W').ordinal)
for f in ['Y', 'Q', 'Q-MAR', 'Y-JUN', 'M', 'W', 'D', 'h']:
    p = pd.Period('2020-05-18 10:20', freq=f)
    print(f, p.year, p.month, p.day, p.hour, p.quarter, p.qyear, p.dayofweek, p.dayofyear, p.days_in_month, p.week)
print(pd.Period('2020-05-18', 'M').strftime('%Y-%m-%d'), pd.Period('2020-05', 'M') + pd.offsets.MonthEnd(2))
try:
    pd.Period('2020-05', 'M') + pd.Period('2020-05', 'M')
except Exception as e: print(type(e).__name__, e)
try:
    pd.Period('2020-05', 'M') - pd.Period('2020-05-01', 'D')
except Exception as e: print(type(e).__name__, e)
try:
    pd.Period('2020-05', 'M') < pd.Period('2020-05-01', 'D')
except Exception as e: print(type(e).__name__, e)
print(pd.Period('2020-05', 'M') == pd.Period('2020-05-01', 'D'))
try: pd.Period('hello', 'M')
except Exception as e: print(type(e).__name__, e)
print(pd.Period('2020-05-18', freq='2M') if False else '')
