import numpy as np, pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [1.5, 2.5, np.nan, 4.5], 'c': list('xyxz'), 'd': pd.Categorical(list('pqpp')),
                   'e': [True, False, True, True], 'f': pd.date_range('2020-01-01', periods=4), 'g': pd.to_timedelta([1, 2, 3, 4], unit='D')})
print(df.describe())
print(df.describe(include='all').to_string())
print(df.describe(include=[np.number]))
print(df.describe(include=[str]))
print(df.describe(include=['category', 'bool']))
print(df.describe(exclude=[np.number]))
print(df.describe(include='number', percentiles=[0.1, 0.9]))
print(df.describe(include=[str, 'datetime']))
print(df[['c', 'e']].describe())
print(df['c'].describe(), df['e'].describe(), df['d'].describe())
print(df.describe(include=np.number).columns.tolist(), df.describe(include=str).columns.tolist())
try: df.describe(include=['nosuch'])
except Exception as e: print(type(e).__name__, e)
try: df[['a']].describe(include=[str])
except Exception as e: print(type(e).__name__, e)
try: df.describe(include='all', exclude=[np.number])
except Exception as e: print(type(e).__name__, e)
s = pd.Series([1.0, np.nan, 3.0, np.nan, 7.0, 8.0, np.nan, np.nan, 12.0], index=list('abcdefghi'))
print(s.interpolate())
print(s.interpolate(method='linear', limit=1))
print(s.interpolate(limit_direction='both', limit=1))
print(s.interpolate(limit_area='inside'))
print(s.interpolate(limit_area='outside'))
print(pd.Series([np.nan, 1.0, np.nan, 3.0, np.nan]).interpolate(limit_direction='backward'))
print(pd.Series([np.nan, 1.0, np.nan, 3.0, np.nan]).interpolate(limit_direction='both'))
print(pd.Series([1.0, np.nan, 4.0], index=[0, 1, 10]).interpolate(method='index'))
print(pd.Series([1.0, np.nan, np.nan, 4.0]).interpolate(method='zero') if False else '')
print(pd.Series([1.0, np.nan, np.nan, 4.0]).interpolate(method='values'))
print(pd.DataFrame({'a': [1.0, np.nan, 3.0], 'b': [np.nan, 2.0, np.nan]}).interpolate())
print(pd.DataFrame({'a': [1.0, np.nan, 3.0], 'b': [np.nan, 2.0, np.nan]}).interpolate(axis=1))
print(pd.Series([1, np.nan, 3], index=pd.date_range('2020-01-01', periods=3)).interpolate(method='time'))
print(pd.Series([1.0, np.nan, 3.0], index=pd.to_datetime(['2020-01-01', '2020-01-02', '2020-01-10'])).interpolate(method='time'))
print(pd.Series([1.0, np.nan, 3.0], index=pd.to_datetime(['2020-01-01', '2020-01-02', '2020-01-10'])).interpolate())
print(pd.Series([1.0, np.nan, 3.0]).interpolate(inplace=False).dtype)
try: pd.Series(['a', None]).interpolate()
except Exception as e: print(type(e).__name__, e)
print(pd.Series([1, 2, 3]).interpolate())
