import numpy as np, pandas as pd
s = pd.Series([1, None, 3, 4], dtype='Int64')
print(s, s.dtype, repr(s.dtype), str(s.dtype))
print(s.isna().tolist(), s.sum(), s.mean(), s.min(), s.max(), s.count(), s.std())
print(s + 1, s * 2, s / 2, s // 2, s % 2, s ** 2)
print(s + s, s - pd.Series([1, 1, 1, 1], dtype='Int64'))
print(s > 2, s == 3, s != 3, (s > 2).dtype)
print(s.fillna(0), s.dropna(), s.astype('float64'), s.astype('Float64'))
print(s.sort_values(), s.sort_values(ascending=False), s.sort_values(na_position='first'))
print(s.value_counts(), s.value_counts(dropna=False), s.unique(), s.nunique())
print(s.cumsum(), s.cummax(), s.diff())
print(s.to_numpy() if False else '', s.tolist(), s.to_list())
print(s.describe())
print(s.apply(lambda x: x), s.map(lambda x: x))
print(pd.NA, repr(pd.NA), type(pd.NA).__name__, pd.isna(pd.NA), pd.NA + 1, pd.NA == 1, pd.NA > 1, pd.NA ** 0, 1 ** pd.NA, pd.NA * 0)
print(pd.NA & False, pd.NA | True, pd.NA & True, pd.NA | False, True & pd.NA, False | pd.NA, pd.NA ^ True, ~pd.NA if False else '')
try: bool(pd.NA)
except Exception as e: print(type(e).__name__, e)
try: print(int(pd.NA))
except Exception as e: print(type(e).__name__, e)
b = pd.Series([True, None, False], dtype='boolean')
print(b, b.dtype, b & True, b | True, b ^ True, ~b, b.all(), b.any(), b.sum())
print(b & pd.Series([True, True, None], dtype='boolean'), b | pd.Series([False, None, None], dtype='boolean'))
st = pd.Series(['a', None, 'ccc'], dtype='string')
print(st, st.dtype, repr(st.dtype), st.str.len(), st.str.upper(), st.str.contains('c'), st.isna().tolist())
print(st.str.len().dtype, st.str.contains('c').dtype, st == 'a', (st == 'a').dtype, st + 'x')
f = pd.Series([1.5, None, 3.0], dtype='Float64')
print(f, f.dtype, f + 1, f.sum(), f / 0, f.round(0))
print(pd.Series([1, 2, 3], dtype='Int64') / pd.Series([0, 1, 2], dtype='Int64'))
print(pd.array([1, None, 3], dtype='Int64'), pd.array(['a', None], dtype='string'), pd.array([True, None]), pd.array([1, 2]))
print(pd.Series(pd.array([1, None])), pd.Series([1, None]).convert_dtypes(), pd.Series([1.0, 2.0]).convert_dtypes().dtype, pd.Series(['a', None]).convert_dtypes().dtype)
df = pd.DataFrame({'a': pd.array([1, None, 3], dtype='Int64'), 'b': pd.array(['x', None, 'z'], dtype='string'), 'c': pd.array([True, None, False], dtype='boolean'), 'd': [1.5, 2.5, None]})
print(df, df.dtypes, df.isna(), df.isna().sum(), df.describe(), df.dropna(), df.fillna(0) if False else '', df.convert_dtypes().dtypes)
print(df.info())
print(df.groupby('b')['a'].sum(), df.groupby('a').size(), df['a'].astype('object').tolist(), df.sort_values('a'))
print(df['a'].astype('Int32'), df['a'].astype(str).tolist(), df['d'].astype('Int64') if False else '')
print(pd.Series([1, 2, None], dtype='Int8'), pd.Series([1, 2, None], dtype='UInt16'), pd.Series([1, 2], dtype='Int32').dtype)
print(pd.Series([1, None], dtype='Int64').to_numpy() if False else '', pd.Series([1, 2], dtype='Int64').to_numpy(), pd.Series([1, 2], dtype='Int64').to_numpy().dtype)
print(pd.concat([pd.Series([1, None], dtype='Int64'), pd.Series([3], dtype='Int64')]), pd.concat([pd.Series([1], dtype='Int64'), pd.Series([2])]).dtype)
print(pd.Series([1, None, 3], dtype='Int64').where(lambda x: x > 1) if False else '', s.where(s > 2), s.mask(s > 2), s.clip(2, 3))
print(s.loc[1], s.iloc[0], s[s > 2], s.isin([1, 3]), s.index.dtype)
print(pd.isna(s), pd.notna(s), s.hasnans, s.is_unique)
print(pd.Series([1, None, 2], dtype='Int64').rank(), pd.Series([1, None, 2], dtype='Int64').astype('category') if False else '')
print(pd.Series([3, None, 1], dtype='Int64').idxmax(), pd.Series([3, None, 1], dtype='Int64').argmax() if False else '')
print(pd.Series([1, None], dtype='Int64').rolling(2).sum() if False else '')
print(pd.Series([1, 2, 3], dtype='Int64').rolling(2).sum())
