import numpy as np
np.random.seed(42)
r1 = np.random.rand(3)
np.random.seed(42)
r2 = np.random.rand(3)
print(str(r1) == str(r2))
print(r1.shape)
print(all(0.0 <= v < 1.0 for v in r1.tolist()))
print(type(np.random.rand()).__name__)
rn = np.random.randn(4)
print(rn.shape)
ri = np.random.randint(0, 10, size=5)
print(ri.dtype.name)
print(all(0 <= v < 10 for v in ri.tolist()))
scalar_i = np.random.randint(5)
print(type(scalar_i).__name__)
print(0 <= scalar_i < 5)
c = np.random.choice(np.array([10.0, 20.0, 30.0]), size=5)
print(all(v in (10.0, 20.0, 30.0) for v in c.tolist()))
c2 = np.random.choice(5, size=3, replace=False)
print(len(set(c2.tolist())) == 3)
