import numpy as np
print(np.arange(5), np.arange(1, 10, 3), np.arange(0, 1, 0.25), np.arange(5, 0, -2), np.arange(3.0))
print(np.arange(5).dtype, np.arange(5.0).dtype, np.arange(1, 5, dtype=np.uint8))
print(np.linspace(0, 1, 5), np.linspace(0, 1, 4, endpoint=False), np.linspace(2, 3, 1))
print(np.zeros((2, 3)), np.ones(3, dtype=int), np.full((2, 2), 7), np.full(3, 2.5), np.empty(0))
print(np.eye(3), np.eye(2, 3, k=1), np.identity(2, dtype=np.uint8))
print(np.zeros_like(np.arange(4)), np.ones_like(np.arange(4.0)), np.full_like(np.arange(3), 9))
x, y = np.meshgrid(np.arange(3), np.arange(2))
print(x, y, x.shape)
x, y = np.meshgrid(np.arange(3), np.arange(2), indexing="ij")
print(x.shape, y)
a = np.arange(24).reshape(2, 3, 4)
print(a.T.shape, a.transpose(1, 0, 2).shape, np.swapaxes(a, 0, 2).shape, np.moveaxis(a, 0, -1).shape)
print(a.reshape(-1).shape, a.reshape(4, -1).shape, a.ravel()[:5], a.flatten()[-3:])
print(np.concatenate([a, a], axis=0).shape, np.concatenate([a, a], axis=2).shape)
print(np.stack([np.arange(3), np.arange(3)]), np.stack([np.arange(3), np.arange(3)], axis=1))
print(np.vstack([np.arange(3), np.arange(3)]), np.hstack([np.arange(3), np.arange(3)]))
print(np.hstack([np.ones((2, 1)), np.zeros((2, 2))]))
print(np.expand_dims(np.arange(3), 0).shape, np.expand_dims(np.arange(3), -1).shape, np.squeeze(np.zeros((1, 3, 1))).shape)
print(np.flip(np.arange(6).reshape(2, 3)), np.fliplr(np.arange(6).reshape(2, 3)), np.flipud(np.arange(6).reshape(2, 3)))
print(np.roll(np.arange(5), 2), np.roll(np.arange(6).reshape(2, 3), 1, axis=1), np.roll(np.arange(6).reshape(2, 3), -1))
print(np.tile(np.array([1, 2]), (2, 2)), np.repeat(np.array([1, 2]), 3), np.repeat(np.arange(4).reshape(2, 2), 2, axis=1))
print(np.pad(np.ones((2, 2)), 1), np.pad(np.arange(3), (2, 1)), np.pad(np.ones((1, 2)), ((1, 0), (0, 2))))
print(np.diag([1, 2, 3]), np.diag(np.arange(9).reshape(3, 3)), np.diagonal(np.arange(9).reshape(3, 3), 1), np.trace(np.eye(3)))
print(np.array([1, 2, 3]).dtype, np.array([1, 2.5]).dtype, np.array([True, 2]).dtype, np.array([]).dtype, np.array(5).shape)
print(np.array([[1, 2], [3, 4]], dtype=np.float32), np.array([1, 2, 3], dtype=bool), np.array(3.5), np.array([np.uint8(1), np.uint8(2)]).dtype)
print(np.array([np.array([1, 2]), np.array([3, 4])]), np.array([(1, 2), (3, 4)]).shape)
print(np.copy(np.arange(3)), np.ascontiguousarray(np.arange(6).reshape(2, 3).T))
print(np.pi, np.e, np.inf, -np.inf, np.nan, np.newaxis)
