import numpy as np
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(3, 2)
print(a @ b, a.dot(b), np.dot(a, b), np.matmul(a, b))
print(a @ np.array([1, 1, 1]), np.array([1, 1]) @ a, np.array([1, 2, 3]) @ np.array([4, 5, 6]))
print(np.outer(np.array([1, 2]), np.array([3, 4])), np.inner(np.array([1, 2]), np.array([3, 4])))
print((np.arange(8).reshape(2, 2, 2) @ np.arange(4).reshape(2, 2)))
print(np.eye(3) @ np.arange(9.0).reshape(3, 3))
print(np.linalg.norm(np.array([3.0, 4.0])), np.linalg.norm(np.arange(6).reshape(2, 3)), np.linalg.norm(np.arange(6.0).reshape(2, 3), axis=1))
print(np.linalg.norm(np.array([3.0, 4.0]), 1), np.linalg.norm(np.array([3.0, 4.0]), np.inf), np.linalg.norm(np.arange(6.0).reshape(2, 3), 1))
r = np.arange(6, dtype=np.float32).reshape(2, 3) @ np.ones((3, 1), dtype=np.float32)
print(r, r.dtype)
print((np.arange(4, dtype=np.uint8).reshape(2, 2) @ np.arange(4, dtype=np.uint8).reshape(2, 2)))
print(np.trace(np.arange(9).reshape(3, 3)), np.diag(np.arange(9).reshape(3, 3)).sum())
