import numpy as np
a = np.arange(12).reshape(3, 4)
for ax in (None, 0, 1, -1):
    print(ax, a.sum(axis=ax), a.mean(axis=ax), a.max(axis=ax), a.min(axis=ax))
print(a.sum(axis=(0, 1)), a.sum(axis=0, keepdims=True), a.std(axis=1), a.var(axis=0))
print(a.cumsum(), a.cumsum(axis=1), a.cumprod(axis=0))
print(a.argmax(), a.argmax(axis=0), a.argmin(axis=1))
print(a.any(), a.all(), (a > 5).any(axis=0), (a >= 0).all(axis=1))
print(np.prod(np.arange(1, 6)), np.ptp(a), np.count_nonzero(a), np.count_nonzero(a > 3))
f = np.array([0.1, 0.2, 0.3, 0.4])
print(f.sum(), f.mean(), f.std(), f.var(), f.max())
big = np.arange(1000000, dtype=np.float32)
print(big.sum(), big.mean())
print(np.arange(100000, dtype=np.float64).sum() / 3)
print(np.mean([1, 2, 3, 4]), np.sum([[1, 2], [3, 4]], axis=0))
print(np.sum(np.array([[1, 2], [3, 4]], dtype=np.uint8), dtype=np.float32))
print(np.mean(np.array([1, 2], dtype=np.uint8)), np.mean(np.array([[1, 2], [3, 4]]), axis=1))
nan = np.array([1.0, np.nan, 3.0])
print(nan.max(), nan.min(), nan.sum(), nan.argmax(), np.isnan(nan))
