import numpy as np
a = np.array([250, 5, 100], dtype=np.uint8)
print(a + 10)
print(a * 2)
print(a - 10)
print((a + a).dtype)
print(a + np.uint8(10))
print(a.astype(np.int16) + 300)
print(np.clip(a.astype(np.int32) + 100, 0, 255).astype(np.uint8))
print(a.dtype, a.itemsize, a.nbytes, a.shape, a.ndim, a.size)
print(repr(a))
b = np.uint8(200)
c = np.uint8(100)
print(repr(b), b, float(b), int(c), b > c, b == 200)
print(isinstance(b, np.uint8), isinstance(b, np.integer), isinstance(b, np.generic))
print(a / 2)
print(a // 7, a % 7)
print(-a)
print(~a)
print(a > 50, (a > 50).dtype)
print(a.sum(), a.sum().dtype, a.mean(), a.max(), a.min(), a.argmax())
print(np.sqrt(a))
print(a.astype(float) / 255)
print(a.astype(np.float32) / 255)
