import numpy as np
z = np.array([1 + 2j, 3.5 - 4j, -2j])
print(z, z.dtype, repr(z))
print(z + 1, z * 2, z * z, z / (1 + 1j), -z, np.conj(z), z.real, z.imag)
print(np.abs(z), np.angle(np.array([1j, -1.0, 1 + 1j])), np.real(z), np.imag(z))
print(np.exp(1j * np.array([0.0, np.pi / 2, np.pi])).round(10))
print(z.sum(), z.mean(), np.sum(np.array([[1j, 2], [3, 4j]]), axis=0))
print(np.array([1, 2], dtype=np.complex64) * 1.5, np.array([1.5, 2.5]).astype(complex), np.zeros(2, dtype=complex), z == z.conj())
print(np.array([1 + 1j], dtype=np.complex64).dtype, (np.array([1.0], dtype=np.float32) + 1j).dtype, (np.array([1.0]) + 1j).dtype, (np.arange(3) * 1j).dtype)
print(np.sqrt(np.array([-4 + 0j, 9 + 0j])), np.array([1j]) ** 2, np.array([1 + 1j]) ** 2.5)
print(np.fft.fft(np.array([1.0, 2.0, 3.0, 4.0])))
print(np.fft.fft(np.array([1.0, 0.0, 0.0, 0.0, 0.0])))
print(np.round(np.abs(np.fft.fft(np.arange(6.0))), 8), np.round(np.fft.fft(np.arange(7.0)), 8))
print(np.fft.ifft(np.fft.fft(np.array([3.0, 1.0, 4.0, 1.0, 5.0]))).real.round(10))
x = np.arange(16.0).reshape(4, 4)
F = np.fft.fft2(x)
print(np.round(F, 8))
print(np.round(np.abs(F), 8), np.round(np.fft.ifft2(F).real, 10))
print(np.fft.fftshift(np.arange(5)), np.fft.ifftshift(np.arange(5)), np.fft.fftshift(np.arange(6)), np.fft.fftshift(np.arange(12).reshape(3, 4)))
print(np.fft.fftfreq(8), np.fft.fftfreq(5, d=0.5), np.fft.rfftfreq(8), np.fft.rfft(np.arange(8.0)).shape)
print(np.round(np.fft.rfft(np.array([1.0, 2.0, 3.0, 4.0, 5.0])), 8), np.round(np.fft.irfft(np.fft.rfft(np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0]))), 10))
print(np.round(np.fft.fft(np.arange(8.0), norm="ortho"), 8), np.fft.fft(np.arange(4.0)).dtype, np.fft.fft(np.arange(4, dtype=np.float32)).dtype)
img = np.random.default_rng(1).integers(0, 256, (8, 8)).astype(np.float64)
S = np.fft.fftshift(np.fft.fft2(img))
print(np.round(np.log1p(np.abs(S))[3:5, 3:5], 6), np.allclose(np.fft.ifft2(np.fft.ifftshift(S)).real, img))
