import numpy as np
rng = np.random.default_rng(42)
print(rng.random(3).tolist())
print(rng.random())
print(rng.integers(0, 10, size=8))
print(rng.integers(5), rng.integers(1, 7), rng.integers(0, 256, size=(2, 3)))
print(rng.integers(0, 256, size=4, dtype=np.uint8).dtype, rng.integers(0, 10, 3).dtype)
print(np.round(rng.normal(size=5), 9))
print(np.round(rng.normal(10, 2, (2, 2)), 9))
print(np.round(rng.standard_normal(3), 9), round(rng.normal(), 9))
print(rng.uniform(-1, 1, 4).tolist())
print(rng.uniform(0, 255, (2, 2)).astype(np.uint8))
print(rng.choice(10, 5, replace=False), rng.choice(10, 6))
print(rng.choice(np.array([0.5, 1.5, 2.5]), 4), rng.choice(5))
print(rng.permutation(8), rng.permutation(np.arange(5) * 10))
a = np.arange(10)
rng.shuffle(a)
print(a)
rng2 = np.random.default_rng(seed=[1, 2, 3])
print(rng2.integers(0, 100, 5), np.round(rng2.normal(size=3), 9))
print(np.random.default_rng(0).random(2).tolist(), np.random.default_rng(2**40 + 7).integers(0, 1000, 4))
img = np.random.default_rng(7).integers(0, 256, (4, 4), dtype=np.uint8)
print(img, img.dtype, img.mean())
noise = np.random.default_rng(3).normal(0, 10, (3, 3))
print(np.round(noise, 6), np.round(noise.std(), 6))
