import numpy as np
a = np.array([[3, 1, 2], [9, 7, 8], [4, 6, 5]])
print(np.sort(a), np.sort(a, axis=0), np.sort(a, axis=None))
print(np.argsort(a), np.argsort(a, axis=0), np.argsort(np.array([2.0, np.nan, 1.0, 2.0])))
print(np.sort(np.array([3.5, np.nan, -1.0, 2.0])), np.sort(np.array([200, 5, 100], dtype=np.uint8)))
u = np.array([3, 1, 2, 3, 1, 1])
print(np.unique(u), np.unique(u, return_counts=True), np.unique(u, return_index=True), np.unique(u, return_inverse=True))
print(np.unique(np.array([[1, 2], [2, 3]])), np.unique(np.array([0.5, np.nan, 0.5, np.nan])))
print(np.bincount(np.array([0, 1, 1, 3])), np.bincount(np.array([0, 1, 1]), minlength=5), np.bincount(np.array([0, 1, 1]), weights=np.array([0.5, 1.0, 2.0])))
print(list(map(int, np.unravel_index(5, (2, 3)))), np.unravel_index(np.array([1, 4]), (2, 3)), list(map(int, np.unravel_index(np.argmax(a), a.shape))))
print(np.median(a), np.median(a, axis=0), np.median(a, axis=1), np.median(np.array([1.0, 2.0, 3.0, 4.0])), np.median(np.array([1.0, np.nan])))
print(np.percentile(np.arange(10), 50), np.percentile(np.arange(10), [25, 75]), np.percentile(a, 90, axis=0), np.quantile(np.arange(5.0), 0.3))
print(np.diff(np.array([1, 4, 9, 16])), np.diff(np.array([1, 4, 9, 16]), n=2), np.diff(a, axis=0), np.diff(np.array([True, False, True])))
print(np.gradient(np.array([1.0, 4.0, 9.0, 16.0])), np.gradient(np.array([1, 2, 4, 8])), np.gradient(np.array([1.0, 4.0, 9.0]), 2.0))
gy, gx = np.gradient(np.arange(12.0).reshape(3, 4) ** 2)
print(gy, gx)
print(np.cross(np.array([1, 0, 0]), np.array([0, 1, 0])), np.cross(np.array([1.0, 2.0, 3.0]), np.array([4.0, 5.0, 6.0])))
print(np.cross(np.array([[1, 0, 0], [0, 1, 0]]), np.array([0, 0, 1])))
print(np.convolve(np.array([1, 2, 3]), np.array([0, 1, 0.5])), np.convolve(np.array([1, 2, 3, 4, 5]), np.array([1, 1, 1, 1]), "same"), np.convolve(np.arange(5), np.array([1, 2]), "valid"))
print(np.convolve(np.array([1, 2, 3]), np.array([1, 1, 1, 1, 1]), "same"))
x = np.array([[1.0, 2.0, 4.0, 7.0], [2.0, 1.0, 5.0, 3.0]])
print(np.cov(x), np.cov(x, bias=True), np.cov(x[0], x[1]), np.cov(x.T, rowvar=False))
print(np.corrcoef(x), np.corrcoef(x[0], x[1]))
print(np.cov(np.arange(5)), np.real(np.array([1.5, 2.5])), np.take(np.arange(10) * 2, [1, 3]), np.take(a, [0, 2], axis=1))
b = np.zeros(5, dtype=np.int64)
np.add.at(b, [0, 1, 1, 3, 1], 1)
print(b)
c = np.zeros((2, 3))
np.add.at(c, (np.array([0, 0, 1]), np.array([1, 1, 2])), np.array([1.0, 2.0, 5.0]))
print(c)
print(np.add.reduce(np.arange(6).reshape(2, 3)), np.add.reduce(np.arange(6).reshape(2, 3), axis=1), np.multiply.outer(np.arange(3), np.arange(1, 3)), np.maximum.reduce(np.array([3, 9, 2])))
print(np.add.accumulate(np.array([1, 2, 3, 4])), np.subtract.outer(np.array([10, 20]), np.array([1, 2, 3])))
yy, xx = np.mgrid[0:3, 0:4]
print(yy, xx, yy.shape, yy.dtype)
print(np.mgrid[0:5], np.mgrid[0.0:1.0:0.25], np.mgrid[1:4, 2:4].shape)
print(np.s_[1:3], np.s_[::2, 1], np.arange(12).reshape(3, 4)[np.s_[1:, ::2]])
