# GENERATED by tools/oracle/gen_torchvision.py from torchvision 0.25.0+cpu (models/mobilenet.py); BSD-3-Clause, Copyright (c) Soumith Chintala 2016.
# Do not edit by hand: change the generator or add a hand-written override instead.
from torchvision.models.mobilenetv2 import *  # noqa: F401, F403
from torchvision.models.mobilenetv3 import *  # noqa: F401, F403
from torchvision.models.mobilenetv2 import __all__ as mv2_all
from torchvision.models.mobilenetv3 import __all__ as mv3_all

__all__ = mv2_all + mv3_all
