import torch

torch.manual_seed(0)
a = torch.randn(3)
print(a)
x = torch.tensor([[1., 2.], [3., 4.]])
print(x, x.shape, x.dtype, x.ndim)
print(x + 1, x * x, x @ x, x.T)
print(x.sum(), x.mean(dim=0), x.max(), x.argmax(), x.sum(dim=1, keepdim=True))
print(torch.arange(6).reshape(2, 3), torch.zeros(2, 2), torch.ones(3, dtype=torch.int32))
print(torch.tensor([1, 2, 3]) / 2, torch.tensor([1, 2, 3]) * 2.5, 2 - torch.tensor([1., 2.]))
print(x[0], x[:, 1], x[x > 2], x.view(4), x.reshape(-1, 1).shape)
w = torch.tensor([1., 2., 3.], requires_grad=True)
y = (w ** 2).sum()
y.backward()
print(w.grad, y, y.item(), w)
print(torch.relu(torch.tensor([-1., 0., 2.])), torch.sigmoid(torch.zeros(2)))
print(torch.linspace(0, 1, 5), torch.eye(2), torch.full((2,), 7))
print(torch.cat([x, x], dim=0).shape, torch.stack([x, x]).shape)
print(torch.rand(2, 2), torch.randint(0, 10, (4,)), torch.randperm(5))
print(x.float().dtype, x.long(), x.numpy(), x.tolist(), len(x), x.numel())
