import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(0)
lin = nn.Linear(3, 2)
print(lin.weight, lin.bias)
x = torch.randn(4, 3)
print(lin(x))
print(lin)
net = nn.Sequential(nn.Linear(3, 4), nn.ReLU(), nn.Linear(4, 1))
print(net)
print([n for n, _ in net.named_parameters()], sum(p.numel() for p in net.parameters()))
y = net(x)
print(y.shape, y.sum())
loss = F.mse_loss(y, torch.zeros(4, 1))
print(loss)
loss.backward()
print(net[0].weight.grad.shape, net[2].bias.grad)

torch.manual_seed(1)
model = nn.Sequential(nn.Linear(2, 8), nn.Tanh(), nn.Linear(8, 1))
opt = torch.optim.Adam(model.parameters(), lr=0.05)
X = torch.randn(32, 2)
Y = (X[:, :1] * 2 - X[:, 1:] * 0.5)
for step in range(5):
    opt.zero_grad()
    l = F.mse_loss(model(X), Y)
    l.backward()
    opt.step()
    print(step, round(l.item(), 6))
sgd = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
for step in range(3):
    sgd.zero_grad()
    l = ((model(X) - Y) ** 2).mean()
    l.backward()
    sgd.step()
    print(step, round(l.item(), 6))

torch.manual_seed(2)
conv = nn.Conv2d(1, 2, 3, padding=1)
img = torch.randn(1, 1, 5, 5)
out = conv(img)
print(out.shape, out.sum().item())
pool = nn.MaxPool2d(2)
print(pool(out).shape, nn.AdaptiveMaxPool2d(1)(out).shape)
bn = nn.BatchNorm2d(2)
print(bn(out).mean().item(), bn.running_mean)
print(F.cross_entropy(torch.tensor([[2.0, 1.0, 0.1]]), torch.tensor([0])))
print(F.softmax(torch.tensor([1.0, 2.0, 3.0]), dim=0), F.binary_cross_entropy_with_logits(torch.tensor([0.5]), torch.tensor([1.0])))
sd = model.state_dict()
print(list(sd.keys()))
emb = nn.Embedding(5, 3)
print(emb(torch.tensor([0, 2])).shape)
