import torch

x = torch.arange(12.).reshape(3, 4)
x[0, 1] = 50
x[:, 0] = torch.tensor([7., 8., 9.])
x[x > 10] = -1
print(x, x[[0, 2]], x[-1], x[..., 1], x[None].shape, x[:, None, 2].shape)
print(x.std(), x.var(dim=1), x.std(dim=0, keepdim=True), x.prod(dim=1), x.cumsum(dim=1))
v, i = x.max(dim=1)
print(v, i, x.max(dim=0).values, x.min(), x.argmin(dim=1))
print(torch.topk(torch.tensor([3., 1., 4., 1., 5.]), 2), torch.sort(torch.tensor([3, 1, 2]), descending=True))
print(torch.unique(torch.tensor([3, 1, 3, 2, 1])), torch.where(x > 5, x, torch.zeros_like(x)))
print(x.clamp(0, 5), x.clamp(min=2), x.norm(), x.norm(dim=1), x.amax(dim=1))
a = torch.tensor([1, 2, 3])
print(a + 1.5, a * torch.tensor([0.5]), a.dtype, (a > 1).sum(), (a > 1).dtype, a / a, a // 2, a % 2, a ** 2)
u = torch.tensor([250, 5], dtype=torch.uint8)
print(u + 10, u.dtype, torch.tensor([1.5], dtype=torch.float64) * 2, torch.tensor([True, False]).sum())
b = torch.zeros(2, 3)
b.add_(1).mul_(3)
b[0].fill_(9)
b.clamp_(max=5)
print(b, b.copy_(torch.ones(2, 3)))
w = torch.tensor([1., 2.], requires_grad=True)
(w * 3).sum().backward()
(w * 3).sum().backward()
print(w.grad, w.requires_grad, w.detach().requires_grad, w.is_leaf)
with torch.no_grad():
    z = w * 2
print(z.requires_grad)
p = torch.tensor([2.0], requires_grad=True)
q = p ** 3
g, = torch.autograd.grad(q, p, create_graph=True)
print(g.item(), g.requires_grad, torch.autograd.grad(g, p)[0])
m = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)
(m * m).backward(torch.ones(2, 2))
print(m.grad)
print(x.permute(1, 0).shape, x.transpose(0, 1).shape, x.chunk(2, dim=1)[0].shape, torch.stack([x, x], dim=1).shape)
print(x.expand(2, 3, 4).shape, torch.tensor([1, 2]).repeat(2, 2), x.flatten().shape, torch.zeros(1, 3, 1).squeeze().shape, torch.cat([x, x], dim=1).shape)
gx, gy = torch.meshgrid(torch.arange(2), torch.arange(3), indexing="ij")
print(gx, gy)
print(torch.tensor([1.0, float("nan"), float("inf")]), torch.tensor([1e-5, 1.0]), torch.tensor([1e10, 1.0]), torch.tensor([0.1, 0.25]).double())
print(torch.tensor([[1, 2], [3, 4]]).T, torch.einsum("ij,jk->ik", x[:, :2], torch.ones(2, 2)))
print(torch.randn(2, 3, generator=torch.Generator().manual_seed(7)), torch.rand(3).dtype)
print(torch.tensor(3.5).item(), torch.tensor([1, 2]).tolist(), float(torch.tensor(2.5)), int(torch.tensor(3)), f"{torch.tensor(1.23456):.2f}")
print(torch.zeros(2, 2) == 0, torch.equal(torch.ones(2), torch.ones(2)), torch.allclose(torch.ones(2), torch.ones(2) + 1e-9))
print(torch.finfo(torch.float32).eps, torch.tensor([1, 2]).shape == (2,), tuple(torch.zeros(2, 3).shape), len(torch.zeros(5, 2)))
