// <auto-generated> by tools/oracle/gen_ndsharp_tests.py — do not edit. Expected values are numpy 2.5.3 repr()s. </auto-generated>
// Copyright (c) 2026 Marco Parenzan
// Licensed under the MIT License. See the LICENSE file in the project root for full license information.

using NDSharp;

namespace NDSharp.Tests;

public partial class OracleTests
{
    [Fact] public void zeros_2x3() => Check("array([[0., 0., 0.],\n       [0., 0., 0.]])", np.Zeros(new[]{2,3}));
    [Fact] public void ones_u8() => Check("array([1, 1, 1], dtype=uint8)", np.Ones(new[]{3}, DType.UInt8));
    [Fact] public void full_int() => Check("array([[7, 7],\n       [7, 7]])", np.Full(new[]{2,2}, 7L));
    [Fact] public void full_float() => Check("array([2.5, 2.5])", np.Full(new[]{2}, 2.5));
    [Fact] public void full_bool() => Check("array([ True,  True])", np.Full(new[]{2}, true));
    [Fact] public void arange_int() => Check("array([0, 1, 2, 3, 4])", np.Arange(0L, 5L));
    [Fact] public void arange_step() => Check("array([1, 4, 7])", np.Arange(1L, 10L, 3L));
    [Fact] public void arange_float() => Check("array([0.  , 0.25, 0.5 , 0.75])", np.Arange(0.0, 1.0, 0.25));
    [Fact] public void arange_neg() => Check("array([5, 3, 1])", np.Arange(5L, 0L, -2L));
    [Fact] public void linspace() => Check("array([ 0. ,  2.5,  5. ,  7.5, 10. ])", np.Linspace(0, 10, 5));
    [Fact] public void linspace_noend() => Check("array([0.  , 0.25, 0.5 , 0.75])", np.Linspace(0, 1, 4, false));
    [Fact] public void eye() => Check("array([[1., 0., 0.],\n       [0., 1., 0.],\n       [0., 0., 1.]])", np.Eye(3));
    [Fact] public void eye_k() => Check("array([[0., 1., 0.],\n       [0., 0., 1.],\n       [0., 0., 0.]])", np.Eye(3, null, 1));
    [Fact] public void eye_i32() => Check("array([[1, 0],\n       [0, 1]], dtype=int32)", np.Eye(2, null, 0, DType.Int32));
    [Fact] public void diag_build() => Check("array([[1, 0, 0],\n       [0, 2, 0],\n       [0, 0, 3]])", np.Diag(L(1,2,3)));
    [Fact] public void diag_extract() => Check("array([0, 4, 8])", np.Diag(np.Reshape(np.Arange(0L,9L),3,3)));
    [Fact] public void zeros_like_u8() => Check("array([0, 0], dtype=uint8)", np.ZerosLike(U8(1,2)));
    [Fact] public void full_like() => Check("array([3., 3.])", np.FullLike(A(1,2), 3L));
    [Fact] public void meshgrid_x() => Check("array([[1., 2., 3.],\n       [1., 2., 3.]])", np.Meshgrid(new[]{A(1,2,3), A(4,5)})[0]);
    [Fact] public void meshgrid_y() => Check("array([[4., 4., 4.],\n       [5., 5., 5.]])", np.Meshgrid(new[]{A(1,2,3), A(4,5)})[1]);
    [Fact] public void meshgrid_ij() => Check("array([[4., 5.],\n       [4., 5.],\n       [4., 5.]])", np.Meshgrid(new[]{A(1,2,3), A(4,5)}, false)[1]);
    [Fact] public void astype_f2u8() => Check("array([255,  44, 255,   3], dtype=uint8)", A(-1.5, 300.7, 255.9, 3.2).AsType(DType.UInt8));
    [Fact] public void astype_f2i8() => Check("array([ 127, -128,  127], dtype=int8)", A(127.9, 128.0, -129.0).AsType(DType.Int8));
    [Fact] public void astype_i2u8() => Check("array([255,   0,   1,  44], dtype=uint8)", L(-1, 256, 257, 300).AsType(DType.UInt8));
    [Fact] public void astype_f2bool() => Check("array([False,  True,  True])", A(0.0, -0.5, double.NaN).AsType(DType.Bool));
    [Fact] public void astype_bool2f() => Check("array([1., 0.], dtype=float32)", B(true,false).AsType(DType.Float32));
    [Fact] public void astype_f64_f32() => Check("array([0.1       , 0.33333334], dtype=float32)", A(0.1, 1.0/3).AsType(DType.Float32));
    [Fact] public void astype_nan_i32() => Check("array([-2147483648, -2147483648], dtype=int32)", A(double.NaN, 1e10).AsType(DType.Int32));
    [Fact] public void u8_add_weak() => Check("array([  4,  15, 110], dtype=uint8)", np.Add(U8(250,5,100), W(10L)));
    [Fact] public void u8_mul_weak() => Check("array([244,  10, 200], dtype=uint8)", np.Multiply(U8(250,5,100), W(2L)));
    [Fact] public void u8_sub_weak() => Check("array([240, 251,  90], dtype=uint8)", np.Subtract(U8(250,5,100), W(10L)));
    [Fact] public void u8_add_u8() => Check("array([ 4, 15, 44], dtype=uint8)", np.Add(U8(250,5,100), U8(10,10,200)));
    [Fact] public void u8_add_i8() => Check("array([249,   4], dtype=int16)", np.Add(U8(250,5), I8(-1,-1)));
    [Fact] public void u8_add_i16() => Check("array([251,   6], dtype=int16)", np.Add(U8(250,5), U8(1,1).AsType(DType.Int16)));
    [Fact] public void u8_plus_float_weak() => Check("array([2.5, 3.5])", np.Add(U8(1,2), W(1.5)));
    [Fact] public void f32_mul_weak_float() => Check("array([0.1, 0.2, 0.3], dtype=float32)", np.Multiply(F32(1,2,3), W(0.1)));
    [Fact] public void i8_plus_float_weak() => Check("array([2.5, 3.5])", np.Add(I8(1,2), W(1.5)));
    [Fact] public void bool_plus_int_weak() => Check("array([2, 1])", np.Add(B(true,false), W(1L)));
    [Fact] public void bool_add_bool() => Check("array([ True,  True])", np.Add(B(true,false), B(true,true)));
    [Fact] public void bool_mul_bool() => Check("array([ True, False])", np.Multiply(B(true,false), B(true,true)));
    [Fact] public void i64_div() => Check("array([0.5, 1. , 1.5])", np.Divide(L(1,2,3), W(2L)));
    [Fact] public void u8_div_u8() => Check("array([0.5, 1. , 1.5])", np.Divide(U8(1,2,3), U8(2,2,2)));
    [Fact] public void f32_div() => Check("array([0.33333334, 0.6666667 , 1.        ], dtype=float32)", np.Divide(F32(1,2,3), W(3L)));
    [Fact] public void floordiv_int() => Check("array([-4,  3, -4,  3])", np.FloorDivide(L(-7,7,-7,7), W(2L)));
    [Fact] public void floordiv_int_neg() => Check("array([ 3, -4])", np.FloorDivide(L(-7,7), W(-2L)));
    [Fact] public void mod_int() => Check("array([2, 1, 2, 1])", np.Mod(L(-7,7,-7,7), W(3L)));
    [Fact] public void mod_int_negdiv() => Check("array([-1, -2])", np.Mod(L(-7,7), W(-3L)));
    [Fact] public void floordiv_float() => Check("array([-4.,  3., -1.])", np.FloorDivide(A(-7.5,7.5,-0.5), W(2L)));
    [Fact] public void mod_float() => Check("array([0.5, 1.5, 1.5])", np.Mod(A(-7.5,7.5,5.5), W(2L)));
    [Fact] public void pow_int() => Check("array([1, 4, 9])", np.Power(L(1,2,3), W(2L)));
    [Fact] public void pow_int_rscalar() => Check("array([2, 4, 8])", np.Power(W(2L), L(1,2,3)));
    [Fact] public void pow_float() => Check("array([1.        , 1.41421356, 1.73205081])", np.Power(A(1,2,3), W(0.5)));
    [Fact] public void pow_u8_wrap() => Check("array([16, 81,  0], dtype=uint8)", np.Power(U8(2,3,16), W(4L)));
    [Fact] public void neg_i64() => Check("array([-1,  2, -3])", np.Negative(L(1,-2,3)));
    [Fact] public void neg_u8_wrap() => Check("array([255, 254], dtype=uint8)", np.Negative(U8(1,2)));
    [Fact] public void abs_i8() => Check("array([   3,    4, -128], dtype=int8)", np.Abs(I8(-3,4,-128)));
    [Fact] public void sign_f() => Check("array([-1.,  0.,  1.])", np.Sign(A(-2.5,0,3)));
    [Fact] public void square_u8() => Check("array([100, 144], dtype=uint8)", np.Square(U8(10,20)));
    [Fact] public void sqrt_f64() => Check("array([1., 2., 3.])", np.Sqrt(A(1,4,9)));
    [Fact] public void sqrt_u8_f16() => Check("array([1., 2., 3.], dtype=float16)", np.Sqrt(U8(1,4,9)));
    [Fact] public void sqrt_i16_f32() => Check("array([1., 2., 3.], dtype=float32)", np.Sqrt(I8(1,4,9).AsType(DType.Int16)));
    [Fact] public void sqrt_i64() => Check("array([1., 2., 3.])", np.Sqrt(L(1,4,9)));
    [Fact] public void log_f64() => Check("array([0.        , 1.        , 2.30258509])", np.Log(A(1, Math.E, 10)));
    [Fact] public void sin_cos() => Check("array([1.        , 1.38177329])", np.Add(np.Sin(A(0,1)), np.Cos(A(0,1))));
    [Fact] public void arctan2() => Check("array([ 2.35619449, -2.35619449])", np.Arctan2(A(1,-1), A(-1,-1)));
    [Fact] public void hypot() => Check("array([ 5., 13.])", np.Hypot(A(3,5), A(4,12)));
    [Fact] public void degrees() => Check("array([  0., 180.,  90.])", np.Degrees(A(0, Math.PI, Math.PI/2)));
    [Fact] public void radians() => Check("array([0.        , 1.57079633, 3.14159265])", np.Radians(A(0,90,180)));
    [Fact] public void round_half_even() => Check("array([ 0.,  2.,  2., -0., -2.])", np.Round(A(0.5,1.5,2.5,-0.5,-1.5)));
    [Fact] public void round_dec() => Check("array([ 1.2,  5.7, -0. ])", np.Round(A(1.234,5.678,-0.001), 1));
    [Fact] public void round_int() => Check("array([1, 2])", np.Round(L(1,2)));
    [Fact] public void floor_f() => Check("array([ 1., -2.])", np.Floor(A(1.5,-1.5)));
    [Fact] public void ceil_int_keep() => Check("array([1, 2])", np.Ceil(L(1,2)));
    [Fact] public void isnan() => Check("array([False,  True, False])", np.IsNan(A(1, double.NaN, double.PositiveInfinity)));
    [Fact] public void isfinite() => Check("array([ True, False, False])", np.IsFinite(A(1, double.NaN, double.PositiveInfinity)));
    [Fact] public void gt_weak() => Check("array([False, False,  True])", np.Greater(L(1,2,3), W(2L)));
    [Fact] public void eq_arrays() => Check("array([ True, False,  True])", np.Equal(L(1,2,3), L(1,5,3)));
    [Fact] public void lt_u8_big() => Check("array([ True,  True])", np.Less(U8(1,255), W(300L)));
    [Fact] public void eq_nan() => Check("array([False,  True])", np.Equal(A(double.NaN,1), A(double.NaN,1)));
    [Fact] public void invert_bool() => Check("array([False,  True])", np.Invert(B(true,false)));
    [Fact] public void invert_u8() => Check("array([255, 254,   0], dtype=uint8)", np.Invert(U8(0,1,255)));
    [Fact] public void invert_i64() => Check("array([-1, -2,  0])", np.Invert(L(0,1,-1)));
    [Fact] public void and_i64() => Check("array([4, 2])", np.BitwiseAnd(L(12,10), W(6L)));
    [Fact] public void or_u8() => Check("array([13, 11], dtype=uint8)", np.BitwiseOr(U8(12,10), W(1L)));
    [Fact] public void xor_bool() => Check("array([False,  True,  True])", np.BitwiseXor(B(true,false,true), B(true,true,false)));
    [Fact] public void shl() => Check("array([ 8, 16])", np.LeftShift(L(1,2), W(3L)));
    [Fact] public void shr_neg() => Check("array([-4,  4])", np.RightShift(L(-8,8), W(1L)));
    [Fact] public void logical_and() => Check("array([False,  True, False])", np.LogicalAnd(L(0,1,2), L(1,1,0)));
    [Fact] public void logical_not() => Check("array([ True, False, False])", np.LogicalNot(L(0,1,2)));
    [Fact] public void where_scalar() => Check("array([0, 0, 3])", np.Where(np.Greater(L(1,2,3), W(2L)), L(1,2,3), W(0L)));
    [Fact] public void where_f() => Check("array([ 1., 20.])", np.Where(B(true,false), A(1,2), A(10,20)));
    [Fact] public void where_u8_weak() => Check("array([  1, 200], dtype=uint8)", np.Where(B(true,false), U8(1,2), W(200L)));
    [Fact] public void clip_i64() => Check("array([  0,   0, 255, 100])", np.Clip(L(-5,0,300,100), W(0L), W(255L)));
    [Fact] public void clip_u8() => Check("array([ 10, 100, 200], dtype=uint8)", np.Clip(U8(0,100,250), W(10L), W(200L)));
    [Fact] public void clip_f_into() => Check("array([0. , 0.5, 1. ])", np.Clip(A(-1.5,0.5,9.0), W(0.0), W(1.0)));
    [Fact] public void maximum_nan() => Check("array([ 2., nan, nan])", np.Maximum(A(1,double.NaN,3), A(2,2,double.NaN)));
    [Fact] public void minimum() => Check("array([1, 2])", np.Minimum(L(1,5), L(3,2)));
    [Fact] public void bcast_col_row() => Check("array([[0, 1, 2, 3],\n       [1, 2, 3, 4],\n       [2, 3, 4, 5]])", np.Add(np.Reshape(np.Arange(0L,3L),3,1), np.Arange(0L,4L)));
    [Fact] public void bcast_mul() => Check("array([[10, 20, 30],\n       [20, 40, 60]])", np.Multiply(LM(new long[,]{{1},{2}}), L(10,20,30)));
    [Fact] public void bcast_to() => Check("array([[1, 2, 3],\n       [1, 2, 3]])", np.BroadcastTo(L(1,2,3), new[]{2,3}));
    [Fact] public void bcast_scalar_arr() => Check("array([9, 8, 7])", np.Subtract(W(10L), L(1,2,3)));
    [Fact] public void sum_i64() => Check("array(6)", np.Sum(L(1,2,3)));
    [Fact] public void sum_u8_widens() => Check("array(300, dtype=uint64)", np.Sum(U8(200,100)));
    [Fact] public void sum_f32() => Check("array(0.6, dtype=float32)", np.Sum(F32(0.1f,0.2f,0.3f)));
    [Fact] public void sum_bool() => Check("array(2)", np.Sum(B(true,true,false)));
    [Fact] public void sum_axis0() => Check("array([3, 5, 7])", np.Sum(np.Reshape(np.Arange(0L,6L),2,3), new[]{0}));
    [Fact] public void sum_axis1() => Check("array([ 3, 12])", np.Sum(np.Reshape(np.Arange(0L,6L),2,3), new[]{1}));
    [Fact] public void sum_axis_neg() => Check("array([ 3, 12])", np.Sum(np.Reshape(np.Arange(0L,6L),2,3), new[]{-1}));
    [Fact] public void sum_keepdims() => Check("array([[ 3],\n       [12]])", np.Sum(np.Reshape(np.Arange(0L,6L),2,3), new[]{1}, true));
    [Fact] public void sum_axes_tuple() => Check("array([ 60,  92, 124])", np.Sum(np.Reshape(np.Arange(0L,24L),2,3,4), new[]{0,2}));
    [Fact] public void sum_T() => Check("array([ 3, 12])", np.Sum(np.Transpose(np.Reshape(np.Arange(0L,6L),2,3)), new[]{0}));
    [Fact] public void prod_i64() => Check("array(24)", np.Prod(L(1,2,3,4)));
    [Fact] public void prod_empty() => Check("array(1.)", np.Prod(np.Zeros(new[]{0})));
    [Fact] public void sum_empty() => Check("array(0.)", np.Sum(np.Zeros(new[]{0})));
    [Fact] public void mean_int() => Check("array(2.5)", np.Mean(L(1,2,3,4)));
    [Fact] public void mean_f32() => Check("array(0.2, dtype=float32)", np.Mean(F32(0.1f,0.2f,0.3f)));
    [Fact] public void mean_axis() => Check("array([1.5, 2.5, 3.5])", np.Mean(np.Reshape(np.Arange(0L,6L),2,3), new[]{0}));
    [Fact] public void mean_u8() => Check("array(185.)", np.Mean(U8(200,100,255)));
    [Fact] public void std() => Check("array(1.11803399)", np.Std(A(1,2,3,4)));
    [Fact] public void var_ddof() => Check("array(1.66666667)", np.Var(A(1,2,3,4), null, false, 1));
    [Fact] public void var_axis() => Check("array([0.66666667, 0.66666667])", np.Var(np.Reshape(np.Arange(0L,6L),2,3), new[]{1}));
    [Fact] public void std_int_axis0() => Check("array([1.5, 1.5, 1.5])", np.Std(np.Reshape(np.Arange(0L,6L),2,3), new[]{0}));
    [Fact] public void max_i8() => Check("array(4, dtype=int8)", np.Max(I8(-3,4,2)));
    [Fact] public void min_axis() => Check("array([5, 8])", np.Min(np.Reshape(np.Arange(5L,11L),2,3), new[]{1}));
    [Fact] public void max_nan() => Check("array(nan)", np.Max(A(1,double.NaN,3)));
    [Fact] public void max_bool() => Check("array(True)", np.Max(B(true,false)));
    [Fact] public void ptp() => Check("array(4.)", np.Ptp(A(1,5,3)));
    [Fact] public void argmax_flat() => Check("array(1)", np.ArgMax(LM(new long[,]{{1,9},{3,2}})));
    [Fact] public void argmax_axis0() => Check("array([1, 0])", np.ArgMax(LM(new long[,]{{1,9},{3,2}}), 0));
    [Fact] public void argmin_axis1() => Check("array([0, 1])", np.ArgMin(LM(new long[,]{{1,9},{3,2}}), 1));
    [Fact] public void argmax_nan() => Check("array(1)", np.ArgMax(A(1,double.NaN,3)));
    [Fact] public void argmax_ties() => Check("array(0)", np.ArgMax(L(3,3,1)));
    [Fact] public void cumsum_flat() => Check("array([ 1,  3,  6, 10])", np.CumSum(LM(new long[,]{{1,2},{3,4}})));
    [Fact] public void cumsum_axis() => Check("array([[1, 2],\n       [4, 6]])", np.CumSum(LM(new long[,]{{1,2},{3,4}}), 0));
    [Fact] public void cumsum_u8() => Check("array([200, 300], dtype=uint64)", np.CumSum(U8(200,100)));
    [Fact] public void cumprod() => Check("array([ 1,  2,  6, 24])", np.CumProd(L(1,2,3,4)));
    [Fact] public void any_axis() => Check("array([False,  True])", np.Any(LM(new long[,]{{0,0},{0,3}}), new[]{1}));
    [Fact] public void all_axis() => Check("array([False,  True])", np.All(LM(new long[,]{{1,2},{0,3}}), new[]{0}));
    [Fact] public void count_nonzero() => Check("array(2)", np.CountNonzero(L(0,1,2,0)));
    [Fact] public void norm() => Check("array(5.)", np.Norm(A(3,4)));
    [Fact] public void norm_axis() => Check("array([ 5., 10.])", np.Norm(M_(new double[,]{{3,4},{6,8}}), new[]{1}));
    [Fact] public void reshape_neg1() => Check("array([[0, 1],\n       [2, 3],\n       [4, 5]])", np.Reshape(np.Arange(0L,6L), 3, -1));
    [Fact] public void transpose_2d() => Check("array([[0, 3],\n       [1, 4],\n       [2, 5]])", np.Transpose(np.Reshape(np.Arange(0L,6L),2,3)));
    [Fact] public void transpose_axes() => Check("array([[[ 0,  1,  2,  3],\n        [12, 13, 14, 15]],\n\n       [[ 4,  5,  6,  7],\n        [16, 17, 18, 19]],\n\n       [[ 8,  9, 10, 11],\n        [20, 21, 22, 23]]])", np.Transpose(np.Reshape(np.Arange(0L,24L),2,3,4), new[]{1,0,2}));
    [Fact] public void swapaxes() => Check("array([[[ 0, 12],\n        [ 4, 16],\n        [ 8, 20]],\n\n       [[ 1, 13],\n        [ 5, 17],\n        [ 9, 21]],\n\n       [[ 2, 14],\n        [ 6, 18],\n        [10, 22]],\n\n       [[ 3, 15],\n        [ 7, 19],\n        [11, 23]]])", np.SwapAxes(np.Reshape(np.Arange(0L,24L),2,3,4), 0, 2));
    [Fact] public void moveaxis() => Check("array([[[ 0, 12],\n        [ 1, 13],\n        [ 2, 14],\n        [ 3, 15]],\n\n       [[ 4, 16],\n        [ 5, 17],\n        [ 6, 18],\n        [ 7, 19]],\n\n       [[ 8, 20],\n        [ 9, 21],\n        [10, 22],\n        [11, 23]]])", np.MoveAxis(np.Reshape(np.Arange(0L,24L),2,3,4), 0, -1));
    [Fact] public void ravel_T() => Check("array([0, 3, 1, 4, 2, 5])", np.Ravel(np.Transpose(np.Reshape(np.Arange(0L,6L),2,3))));
    [Fact] public void flatten() => Check("array([0, 1, 2, 3, 4, 5])", np.Flatten(np.Reshape(np.Arange(0L,6L),2,3)));
    [Fact] public void concat_axis1() => Check("array([[ 0,  1, 10, 11],\n       [ 2,  3, 12, 13]])", np.Concatenate(new[]{np.Reshape(np.Arange(0L,4L),2,2), np.Reshape(np.Arange(10L,14L),2,2)}, 1));
    [Fact] public void concat_promote() => Check("array([1. , 2. , 0.5])", np.Concatenate(new[]{L(1,2), A(0.5)}));
    [Fact] public void stack_axis1() => Check("array([[1, 4],\n       [2, 5],\n       [3, 6]])", np.Stack(new[]{L(1,2,3), L(4,5,6)}, 1));
    [Fact] public void vstack_1d() => Check("array([[1, 2],\n       [3, 4]])", np.VStack(new[]{L(1,2), L(3,4)}));
    [Fact] public void hstack_1d() => Check("array([1, 2, 3, 4])", np.HStack(new[]{L(1,2), L(3,4)}));
    [Fact] public void hstack_2d() => Check("array([[1, 3],\n       [2, 4]])", np.HStack(new[]{np.Reshape(L(1,2),2,1), np.Reshape(L(3,4),2,1)}));
    [Fact] public void flip() => Check("array([[2, 1, 0],\n       [5, 4, 3]])", np.Flip(np.Reshape(np.Arange(0L,6L),2,3), 1));
    [Fact] public void fliplr() => Check("array([[2, 1, 0],\n       [5, 4, 3]])", np.Fliplr(np.Reshape(np.Arange(0L,6L),2,3)));
    [Fact] public void flipud() => Check("array([[3, 4, 5],\n       [0, 1, 2]])", np.Flipud(np.Reshape(np.Arange(0L,6L),2,3)));
    [Fact] public void roll_1d() => Check("array([3, 4, 0, 1, 2])", np.Roll(np.Arange(0L,5L), 2, 0));
    [Fact] public void roll_neg() => Check("array([1, 2, 3, 4, 0])", np.Roll(np.Arange(0L,5L), -1, 0));
    [Fact] public void roll_axis1() => Check("array([[2, 0, 1],\n       [5, 3, 4]])", np.Roll(np.Reshape(np.Arange(0L,6L),2,3), 1, 1));
    [Fact] public void roll_flat() => Check("array([[5, 0, 1],\n       [2, 3, 4]])", np.Roll(np.Reshape(np.Arange(0L,6L),2,3), 1));
    [Fact] public void tile() => Check("array([[1, 2, 1, 2],\n       [1, 2, 1, 2]])", np.Tile(L(1,2), 2, 2));
    [Fact] public void repeat() => Check("array([1, 1, 1, 2, 2, 2])", np.Repeat(L(1,2), 3));
    [Fact] public void repeat_axis() => Check("array([[1, 2],\n       [1, 2],\n       [3, 4],\n       [3, 4]])", np.Repeat(np.Reshape(L(1,2,3,4),2,2), 2, 0));
    [Fact] public void expand_dims() => Check("array([[1, 2]])", np.ExpandDims(L(1,2), 0));
    [Fact] public void squeeze() => Check("array([1, 2])", np.Squeeze(np.Reshape(L(1,2),1,2,1)));
    [Fact] public void pad_const() => Check("array([[0, 0, 0, 0],\n       [0, 1, 2, 0],\n       [0, 3, 4, 0],\n       [0, 0, 0, 0]])", np.PadConstant(np.Reshape(L(1,2,3,4),2,2), new[]{(1,1)}));
    [Fact] public void pad_asym() => Check("array([0, 0, 1, 2, 3, 0])", np.PadConstant(L(1,2,3), new[]{(2,1)}));
    [Fact] public void idx_slice() => Check("array([1, 2])", L(0,1,2,3,4).Get(new Slice(1,3)));
    [Fact] public void idx_rev() => Check("array([4, 3, 2, 1, 0])", L(0,1,2,3,4).Get(new Slice(null,null,-1)));
    [Fact] public void idx_step() => Check("array([0, 2, 4])", L(0,1,2,3,4).Get(new Slice(null,null,2)));
    [Fact] public void idx_neg_start() => Check("array([3, 4])", L(0,1,2,3,4).Get(new Slice(-2,null)));
    [Fact] public void idx_col() => Check("array([1, 4])", M6().Get(Slice.All, 1));
    [Fact] public void idx_row() => Check("array([3, 4, 5])", M6().Get(1, Slice.All));
    [Fact] public void idx_int() => Check("array([3, 4, 5])", M6().Get(1));
    [Fact] public void idx_ellipsis() => Check("array([0, 3])", M6().Get(NDIndex.Ellipsis, 0));
    [Fact] public void idx_newaxis() => Check("array([[1, 2, 3]])", L(1,2,3).Get(NDIndex.NewAxis, Slice.All));
    [Fact] public void idx_newaxis_end() => Check("array([[1],\n       [2],\n       [3]])", L(1,2,3).Get(Slice.All, NDIndex.NewAxis));
    [Fact] public void idx_2d_slice() => Check("array([[1, 2],\n       [4, 5]])", M6().Get(new Slice(0,2), new Slice(1,3)));
    [Fact] public void idx_T_slice() => Check("array([2, 1, 0])", np.Transpose(M6()).Get(new Slice(null,null,-1), 0));
    [Fact] public void fancy_1d() => Check("array([10, 30, 30])", L(10,20,30,40).Get(L(0,2,2)));
    [Fact] public void fancy_neg() => Check("array([40, 10])", L(10,20,30,40).Get(L(-1,0)));
    [Fact] public void fancy_2d_rows() => Check("array([[3, 4, 5],\n       [0, 1, 2]])", M6().Get(L(1,0)));
    [Fact] public void fancy_pair() => Check("array([2, 3])", M6().Get(L(0,1), L(2,0)));
    [Fact] public void fancy_cols() => Check("array([[0, 2],\n       [3, 5]])", M6().Get(Slice.All, L(0,2)));
    [Fact] public void fancy_rows_slice() => Check("array([[4, 5],\n       [1, 2]])", M6().Get(L(1,0), new Slice(1,null)));
    [Fact] public void fancy_int_and_arr() => Check("array([2, 0])", M6().Get(0, L(2,0)));
    [Fact] public void fancy_nonadjacent() => Check("array([[ 1,  5,  9],\n       [14, 18, 22]])", np.Reshape(np.Arange(0L,24L),2,3,4).Get(L(0,1), Slice.All, L(1,2)));
    [Fact] public void fancy_2d_index() => Check("array([[10, 20],\n       [30, 40]])", L(10,20,30,40).Get(LM(new long[,]{{0,1},{2,3}})));
    [Fact] public void mask_1d() => Check("array([1, 3])", L(1,2,3,4).Get(B(true,false,true,false)));
    [Fact] public void mask_from_cmp() => Check("array([3, 4, 5])", M6().Get(np.Greater(M6(), W(2L))));
    [Fact] public void mask_rows() => Check("array([[3, 4, 5]])", M6().Get(B(false,true)));
    [Fact] public void mask_and_slice() => Check("array([[0, 1, 2]])", M6().Get(B(true,false), Slice.All));
    [Fact] public void matmul_22() => Check("array([[19., 22.],\n       [43., 50.]])", np.MatMul(M_(new double[,]{{1,2},{3,4}}), M_(new double[,]{{5,6},{7,8}})));
    [Fact] public void matmul_23_32() => Check("array([[ 5, 14],\n       [14, 50]])", np.MatMul(M6(), np.Transpose(M6())));
    [Fact] public void matmul_1d_1d() => Check("array(32)", np.MatMul(L(1,2,3), L(4,5,6)));
    [Fact] public void matmul_2d_1d() => Check("array([ 3, 12])", np.MatMul(M6(), L(1,1,1)));
    [Fact] public void matmul_1d_2d() => Check("array([3, 5, 7])", np.MatMul(L(1,1), M6()));
    [Fact] public void matmul_batch() => Check("array([[[ 2,  3],\n        [ 6, 11]],\n\n       [[10, 19],\n        [14, 27]]])", np.MatMul(np.Reshape(np.Arange(0L,8L),2,2,2), np.Reshape(np.Arange(0L,4L),2,2)));
    [Fact] public void matmul_f32() => Check("array([[11.]], dtype=float32)", np.MatMul(F32(1,2).AsType(DType.Float32).Get(NDIndex.NewAxis, Slice.All), F32(3,4).Get(Slice.All, NDIndex.NewAxis)));
    [Fact] public void matmul_u8() => Check("array(150, dtype=uint8)", np.MatMul(U8(200,2), U8(2,3)));
    [Fact] public void dot_scalar() => Check("array([2, 4])", np.Dot(W(2L), L(1,2)));
    [Fact] public void outer() => Check("array([[10, 20],\n       [20, 40],\n       [30, 60]])", np.Outer(L(1,2,3), L(10,20)));
    [Fact] public void trace() => Check("array(4)", np.Trace(M6().Get(Slice.All, new Slice(0,2))));
    [Fact] public void set_slice() { var x = L(0,1,2,3,4); x.Put(W(9L), new Slice(1,3)); Check("array([0, 9, 9, 3, 4])", x); }
    [Fact] public void set_slice_arr() { var x = L(0,1,2,3,4); x.Put(L(7,8), new Slice(1,3)); Check("array([0, 7, 8, 3, 4])", x); }
    [Fact] public void set_bcast_row() { var x = np.Zeros(new[]{2,3}, DType.Int64); x.Put(L(1,2,3), Slice.All); Check("array([[1, 2, 3],\n       [1, 2, 3]])", x); }
    [Fact] public void set_float_into_int() { var x = L(0,0,0); x.Put(W(2.7), Slice.All); Check("array([2, 2, 2])", x); }
    [Fact] public void set_u8_wrap() { var x = U8(0,0); x.Put(W(300L), Slice.All); Check("array([44, 44], dtype=uint8)", x); }
    [Fact] public void set_mask() { var x = L(1,2,3,4); x.Put(W(0L), B(true,false,true,false)); Check("array([0, 2, 0, 4])", x); }
    [Fact] public void set_mask_cmp() { var x = M6(); x.Put(W(-1L), np.Greater(x, W(2L))); Check("array([[ 0,  1,  2],\n       [-1, -1, -1]])", x); }
    [Fact] public void set_mask_arr() { var x = L(1,2,3,4); x.Put(L(10,30), B(true,false,true,false)); Check("array([10,  2, 30,  4])", x); }
    [Fact] public void set_fancy() { var x = L(0,0,0,0); x.Put(L(5,6), L(0,2)); Check("array([5, 0, 6, 0])", x); }
    [Fact] public void set_fancy_2d() { var x = np.Zeros(new[]{2,3}, DType.Int64); x.Put(W(1L), L(0,1), L(2,0)); Check("array([[0, 0, 1],\n       [1, 0, 0]])", x); }
    [Fact] public void set_view_shares() { var x = M6(); var v = x.Get(1, Slice.All); v.Put(W(0L), Slice.All); Check("array([[0, 1, 2],\n       [0, 0, 0]])", x); }
    [Fact] public void set_T_view() { var x = M6(); np.Transpose(x).Put(W(0L), 0, Slice.All); Check("array([[0, 1, 2],\n       [0, 4, 5]])", x); }
    [Fact] public void set_overlap() { var x = L(0,1,2,3,4); x.Put(x.Get(new Slice(0,4)), new Slice(1,5)); Check("array([0, 0, 1, 2, 3])", x); }
}
