import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle

fig, ax = plt.subplots()
l1, = ax.plot([1, 2, 3], [1, 4, 9], "go--", label="sq")
print(type(l1).__name__, l1.get_label(), len(ax.lines), list(map(float, l1.get_xdata())), list(map(float, l1.get_ydata())))
sc = ax.scatter([1, 2, 3], [3, 2, 1], c=[0.1, 0.5, 0.9], cmap="viridis", s=50, label="pts")
bars = ax.bar([1, 2, 3], [2, 3, 1], label="bars")
print(len(ax.patches), len(ax.collections), len(bars))
ax.add_patch(Circle((2, 2), 0.5, fill=False, edgecolor="r"))
ax.add_patch(Rectangle((0, 0), 1, 1, color="b", alpha=0.3))
print(len(ax.patches))
h, lab = ax.get_legend_handles_labels()
print(lab, len(h))
ax.legend(loc="upper left")
ax.text(1, 1, "hello")
ax.annotate("note", xy=(2, 2), xytext=(2.5, 3), arrowprops=dict(arrowstyle="->"))
print(len(ax.texts))
ax.axhline(2, color="k")
ax.axvline(1.5)
print(len(ax.lines))
x = np.linspace(-2, 2, 30)
X, Y = np.meshgrid(x, x)
Z = np.exp(-(X ** 2 + Y ** 2))
fig, ax = plt.subplots()
cs = ax.contour(X, Y, Z, levels=5)
print(np.round(cs.levels, 3))
cf = ax.contourf(X, Y, Z)
print(np.round(cf.levels, 3))
ax.figure.canvas.draw()
print([float(v) for v in ax.get_xlim()], [float(v) for v in ax.get_ylim()])
fig, axes = plt.subplots(2, 2)
print(axes.shape, type(axes[0, 1]).__name__, len(axes.flat), axes[1].shape, axes[:, 0].shape)
fig, ax = plt.subplots()
ax.fill_between([0, 1, 2], [0, 1, 0], alpha=0.3)
ax.stem([0, 1, 2], [1, 2, 3])
ax.set_xlabel("$\theta$ (rad)")
print(ax.get_xlabel(), len(ax.patches), plt.gca() is ax, plt.gcf() is fig)
plt.close("all")
print(len(plt.get_fignums()))
