import numpy as np
import matplotlib.pyplot as plt

def info(ax):
    ax.figure.canvas.draw()
    print(np.round(ax.get_xlim(), 6), np.round(ax.get_ylim(), 6))
    print(ax.get_xticks(), ax.get_yticks())
    print([t.get_text() for t in ax.get_xticklabels()], [t.get_text() for t in ax.get_yticklabels()])

x = np.linspace(0, 10, 50)
fig, ax = plt.subplots()
ax.plot(x, np.sin(x))
info(ax)
fig, ax = plt.subplots()
ax.plot([1, 2, 3], [100, 2000, 30000])
info(ax)
fig, ax = plt.subplots()
ax.plot(np.arange(5), np.arange(5) * 1e-4)
info(ax)
fig, ax = plt.subplots()
ax.plot([0, 1], [1e7, 3e7])
info(ax)
fig, ax = plt.subplots()
ax.scatter([0.5, 0.7, 0.9], [-3, 4, 1])
info(ax)
fig, ax = plt.subplots()
ax.bar([0, 1, 2, 3], [3, 5, 2, 7])
info(ax)
fig, ax = plt.subplots()
ax.plot([5, 5, 5], [2, 2, 2])
info(ax)
fig, ax = plt.subplots(figsize=(3, 2))
ax.plot(np.arange(100), np.arange(100) ** 2)
info(ax)
fig, ax = plt.subplots()
ax.plot([1, 2, 3], [4, 5, 6])
ax.set_xlim(0, 10)
ax.set_yticks([4., 5., 6.], ["a", "b", "c"])
ax.invert_yaxis()
info(ax)
fig, ax = plt.subplots()
ax.semilogy([1, 2, 3, 4], [1, 10, 100, 1000])
info(ax)
